In [1]:
from pathlib import Path
import os
import sys
import json
import time
import shutil
import subprocess

import numpy as np
import pandas as pd
import cv2
import torch

WORK_DIR = Path("/kaggle/working")
INPUT_DIR = Path("/kaggle/input")

BENCH_DIR = WORK_DIR / "benchmark_results"
BENCH_DIR.mkdir(parents=True, exist_ok=True)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

PATHS = {
    "CLTR_MODEL": INPUT_DIR / "cltr_model",
    "FDST_DATASET": INPUT_DIR / "FDST_dataset",
    "FIDTM_MODEL": INPUT_DIR / "FIDTM-MODEL",
    "MALL_DATASET": INPUT_DIR / "mall_dataset",
    "PET_MODEL": INPUT_DIR / "PET_bestmodel",
    "STEERER_MODELS": INPUT_DIR / "STEERER_models",
}

def inspect_path(path: Path, max_depth: int = 2, max_items: int = 20, prefix: str = ""):
    if not path.exists():
        print(prefix + f"[MISSING] {path}")
        return
    
    print(prefix + f"[DIR] {path}")
    
    if max_depth <= 0:
        return
    
    try:
        items = sorted(list(path.iterdir()), key=lambda x: (x.is_file(), x.name.lower()))
    except Exception as e:
        print(prefix + f"  Cannot read: {e}")
        return
    
    shown = items[:max_items]
    for item in shown:
        if item.is_dir():
            print(prefix + f"  ├── [DIR] {item.name}")
            inspect_path(item, max_depth=max_depth-1, max_items=max_items, prefix=prefix + "  │   ")
        else:
            size_mb = item.stat().st_size / (1024 * 1024)
            print(prefix + f"  ├── [FILE] {item.name} ({size_mb:.2f} MB)")
    
    if len(items) > max_items:
        print(prefix + f"  └── ... {len(items) - max_items} more items not shown")

print("=" * 80)
print("DEVICE:", DEVICE)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
print("Benchmark folder:", BENCH_DIR)
print("=" * 80)

for name, path in PATHS.items():
    print("\n" + "=" * 80)
    print(name)
    print("=" * 80)
    
    if name == "FDST_DATASET":
        inspect_path(path, max_depth=2, max_items=8)
    else:
        inspect_path(path, max_depth=3, max_items=20)

================================================================================
DEVICE: cuda
CUDA available: True
GPU: Tesla T4
Benchmark folder: /kaggle/working/benchmark_results
================================================================================

================================================================================
CLTR_MODEL
================================================================================
[MISSING] /kaggle/input/cltr_model

================================================================================
FDST_DATASET
================================================================================
[MISSING] /kaggle/input/FDST_dataset

================================================================================
FIDTM_MODEL
================================================================================
[MISSING] /kaggle/input/FIDTM-MODEL

================================================================================
MALL_DATASET
================================================================================
[MISSING] /kaggle/input/mall_dataset

================================================================================
PET_MODEL
================================================================================
[MISSING] /kaggle/input/PET_bestmodel

================================================================================
STEERER_MODELS
================================================================================
[MISSING] /kaggle/input/STEERER_models

In [4]:
from pathlib import Path

DATASETS_DIR = Path("/kaggle/input/datasets/yahiaelgayar")

print("Inside /kaggle/input/datasets:")
for p in sorted(DATASETS_DIR.iterdir()):
    print(repr(p.name), "=>", p)

Inside /kaggle/input/datasets:
'cltr-model' => /kaggle/input/datasets/yahiaelgayar/cltr-model
'fdst-dataset' => /kaggle/input/datasets/yahiaelgayar/fdst-dataset
'fidtm-model' => /kaggle/input/datasets/yahiaelgayar/fidtm-model
'mall-dataset' => /kaggle/input/datasets/yahiaelgayar/mall-dataset
'pet-bestmodel' => /kaggle/input/datasets/yahiaelgayar/pet-bestmodel
'steerer-models' => /kaggle/input/datasets/yahiaelgayar/steerer-models

In [5]:
from pathlib import Path
import torch

WORK_DIR = Path("/kaggle/working")
INPUT_BASE = Path("/kaggle/input/datasets/yahiaelgayar")

BENCH_DIR = WORK_DIR / "benchmark_results"
BENCH_DIR.mkdir(parents=True, exist_ok=True)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

PATHS = {
    "CLTR_MODEL": INPUT_BASE / "cltr-model",
    "FDST_DATASET": INPUT_BASE / "fdst-dataset",
    "FIDTM_MODEL": INPUT_BASE / "fidtm-model",
    "MALL_DATASET": INPUT_BASE / "mall-dataset",
    "PET_MODEL": INPUT_BASE / "pet-bestmodel",
    "STEERER_MODELS": INPUT_BASE / "steerer-models",
}

def inspect_path(path: Path, max_depth: int = 2, max_items: int = 12, prefix: str = ""):
    if not path.exists():
        print(prefix + f"[MISSING] {path}")
        return

    print(prefix + f"[DIR] {path}")

    if max_depth <= 0:
        return

    items = sorted(list(path.iterdir()), key=lambda x: (x.is_file(), x.name.lower()))

    for item in items[:max_items]:
        if item.is_dir():
            print(prefix + f"  ├── [DIR] {item.name}")
            inspect_path(item, max_depth=max_depth - 1, max_items=max_items, prefix=prefix + "  │   ")
        else:
            size_mb = item.stat().st_size / (1024 * 1024)
            print(prefix + f"  ├── [FILE] {item.name} ({size_mb:.2f} MB)")

    if len(items) > max_items:
        print(prefix + f"  └── ... {len(items) - max_items} more items not shown")

print("=" * 80)
print("Device:", DEVICE)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
print("Benchmark output:", BENCH_DIR)
print("=" * 80)

for name, path in PATHS.items():
    print("\n" + "=" * 80)
    print(name, "=>", path)
    print("=" * 80)

    if name == "FDST_DATASET":
        inspect_path(path, max_depth=3, max_items=8)
    else:
        inspect_path(path, max_depth=4, max_items=12)

================================================================================
Device: cuda
GPU: Tesla T4
Benchmark output: /kaggle/working/benchmark_results
================================================================================

================================================================================
CLTR_MODEL => /kaggle/input/datasets/yahiaelgayar/cltr-model
================================================================================
[DIR] /kaggle/input/datasets/yahiaelgayar/cltr-model
  ├── [FILE] video_model.pth (496.93 MB)

================================================================================
FDST_DATASET => /kaggle/input/datasets/yahiaelgayar/fdst-dataset
================================================================================
[DIR] /kaggle/input/datasets/yahiaelgayar/fdst-dataset
  ├── [DIR] FDST
  │   [DIR] /kaggle/input/datasets/yahiaelgayar/fdst-dataset/FDST
  │     ├── [DIR] images
  │     │   [DIR] /kaggle/input/datasets/yahiaelgayar/fdst-dataset/FDST/images
  │     │     ├── [FILE] 100_001.jpg (0.46 MB)
  │     │     ├── [FILE] 100_002.jpg (0.51 MB)
  │     │     ├── [FILE] 100_003.jpg (0.51 MB)
  │     │     ├── [FILE] 100_004.jpg (0.44 MB)
  │     │     ├── [FILE] 100_005.jpg (0.39 MB)
  │     │     ├── [FILE] 100_006.jpg (0.34 MB)
  │     │     ├── [FILE] 100_007.jpg (0.31 MB)
  │     │     ├── [FILE] 100_008.jpg (0.28 MB)
  │     │     └── ... 14992 more items not shown
  │     ├── [DIR] jsons
  │     │   [DIR] /kaggle/input/datasets/yahiaelgayar/fdst-dataset/FDST/jsons
  │     │     ├── [FILE] 100_001.json (0.00 MB)
  │     │     ├── [FILE] 100_002.json (0.00 MB)
  │     │     ├── [FILE] 100_003.json (0.00 MB)
  │     │     ├── [FILE] 100_004.json (0.00 MB)
  │     │     ├── [FILE] 100_005.json (0.00 MB)
  │     │     ├── [FILE] 100_006.json (0.00 MB)
  │     │     ├── [FILE] 100_007.json (0.00 MB)
  │     │     ├── [FILE] 100_008.json (0.00 MB)
  │     │     └── ... 14992 more items not shown
  │     ├── [DIR] mask
  │     │   [DIR] /kaggle/input/datasets/yahiaelgayar/fdst-dataset/FDST/mask
  │     │     ├── [FILE] 100_001.png (0.00 MB)
  │     │     ├── [FILE] 100_002.png (0.00 MB)
  │     │     ├── [FILE] 100_003.png (0.00 MB)
  │     │     ├── [FILE] 100_004.png (0.00 MB)
  │     │     ├── [FILE] 100_005.png (0.00 MB)
  │     │     ├── [FILE] 100_006.png (0.00 MB)
  │     │     ├── [FILE] 100_007.png (0.00 MB)
  │     │     ├── [FILE] 100_008.png (0.00 MB)
  │     │     └── ... 14992 more items not shown
  │     ├── [DIR] mask_scale_31
  │     │   [DIR] /kaggle/input/datasets/yahiaelgayar/fdst-dataset/FDST/mask_scale_31
  │     │     ├── [FILE] 100_001.npy (3.96 MB)
  │     │     ├── [FILE] 100_001.png (0.00 MB)
  │     │     ├── [FILE] 100_002.png (0.00 MB)
  │     │     ├── [FILE] 100_003.npy (3.96 MB)
  │     │     ├── [FILE] 100_003.png (0.00 MB)
  │     │     ├── [FILE] 100_005.png (0.00 MB)
  │     │     ├── [FILE] 100_006.npy (3.96 MB)
  │     │     ├── [FILE] 100_008.npy (3.96 MB)
  │     │     └── ... 19037 more items not shown
  │     ├── [FILE] test.txt (0.05 MB)
  │     ├── [FILE] test_gt_loc.txt (2.52 MB)
  │     ├── [FILE] train.txt (0.06 MB)
  │     ├── [FILE] val.txt (0.01 MB)
  │     └── ... 1 more items not shown

================================================================================
FIDTM_MODEL => /kaggle/input/datasets/yahiaelgayar/fidtm-model
================================================================================
[DIR] /kaggle/input/datasets/yahiaelgayar/fidtm-model
  ├── [FILE] model_best_jhu (1).pth (762.98 MB)

================================================================================
MALL_DATASET => /kaggle/input/datasets/yahiaelgayar/mall-dataset
================================================================================
[DIR] /kaggle/input/datasets/yahiaelgayar/mall-dataset
  ├── [DIR] mall_dataset
  │   [DIR] /kaggle/input/datasets/yahiaelgayar/mall-dataset/mall_dataset
  │     ├── [DIR] frames
  │     │   [DIR] /kaggle/input/datasets/yahiaelgayar/mall-dataset/mall_dataset/frames
  │     │     ├── [FILE] seq_000001.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000002.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000003.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000004.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000005.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000006.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000007.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000008.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000009.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000010.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000011.jpg (0.04 MB)
  │     │     ├── [FILE] seq_000012.jpg (0.04 MB)
  │     │     └── ... 1989 more items not shown
  │     ├── [FILE] demo.m (0.00 MB)
  │     ├── [FILE] mall_feat.mat (0.41 MB)
  │     ├── [FILE] mall_gt.mat (0.58 MB)
  │     ├── [FILE] perspective_roi.mat (1.08 MB)
  │     ├── [FILE] readme.txt (0.00 MB)

================================================================================
PET_MODEL => /kaggle/input/datasets/yahiaelgayar/pet-bestmodel
================================================================================
[DIR] /kaggle/input/datasets/yahiaelgayar/pet-bestmodel
  ├── [FILE] JHU_Crowd.pth (79.90 MB)

================================================================================
STEERER_MODELS => /kaggle/input/datasets/yahiaelgayar/steerer-models
================================================================================
[DIR] /kaggle/input/datasets/yahiaelgayar/steerer-models
  ├── [FILE] FDST_mae_0.92_mse_1.29 (1).pth (247.58 MB)
  ├── [FILE] JHU_mae_54.5_mse_240.6.pth (247.58 MB)

In [6]:
PET_WEIGHT_PATH = Path("/kaggle/input/datasets/yahiaelgayar/pet-bestmodel/JHU_Crowd.pth")

print("PET weight:", PET_WEIGHT_PATH)
print("Exists:", PET_WEIGHT_PATH.exists())

PET weight: /kaggle/input/datasets/yahiaelgayar/pet-bestmodel/JHU_Crowd.pth
Exists: True

In [7]:
from pathlib import Path

WORK_DIR = Path("/kaggle/working")
INPUT_BASE = Path("/kaggle/input/datasets/yahiaelgayar")

BENCH_DIR = WORK_DIR / "benchmark_results"
BENCH_DIR.mkdir(parents=True, exist_ok=True)

# Datasets
FDST_ROOT = INPUT_BASE / "fdst-dataset" / "FDST"
FDST_IMAGES_DIR = FDST_ROOT / "images"
FDST_JSONS_DIR = FDST_ROOT / "jsons"

MALL_ROOT = INPUT_BASE / "mall-dataset" / "mall_dataset"
MALL_FRAMES_DIR = MALL_ROOT / "frames"
MALL_GT_MAT = MALL_ROOT / "mall_gt.mat"

# Model weights
FIDTM_WEIGHT_PATH = INPUT_BASE / "fidtm-model" / "model_best_jhu (1).pth"
PET_WEIGHT_PATH = INPUT_BASE / "pet-bestmodel" / "JHU_Crowd.pth"
CLTR_WEIGHT_PATH = INPUT_BASE / "cltr-model" / "video_model.pth"
STEERER_WEIGHT_PATH = INPUT_BASE / "steerer-models" / "JHU_mae_54.5_mse_240.6.pth"

MAX_FDST_FRAMES = 6000

paths_to_check = {
    "FDST_ROOT": FDST_ROOT,
    "FDST_IMAGES_DIR": FDST_IMAGES_DIR,
    "FDST_JSONS_DIR": FDST_JSONS_DIR,
    "MALL_ROOT": MALL_ROOT,
    "MALL_FRAMES_DIR": MALL_FRAMES_DIR,
    "MALL_GT_MAT": MALL_GT_MAT,
    "FIDTM_WEIGHT_PATH": FIDTM_WEIGHT_PATH,
    "PET_WEIGHT_PATH": PET_WEIGHT_PATH,
    "CLTR_WEIGHT_PATH": CLTR_WEIGHT_PATH,
    "STEERER_WEIGHT_PATH": STEERER_WEIGHT_PATH,
}

for name, path in paths_to_check.items():
    print(f"{name}: {path}")
    print("  exists:", path.exists())

print("\nBenchmark output folder:", BENCH_DIR)

FDST_ROOT: /kaggle/input/datasets/yahiaelgayar/fdst-dataset/FDST
  exists: True
FDST_IMAGES_DIR: /kaggle/input/datasets/yahiaelgayar/fdst-dataset/FDST/images
  exists: True
FDST_JSONS_DIR: /kaggle/input/datasets/yahiaelgayar/fdst-dataset/FDST/jsons
  exists: True
MALL_ROOT: /kaggle/input/datasets/yahiaelgayar/mall-dataset/mall_dataset
  exists: True
MALL_FRAMES_DIR: /kaggle/input/datasets/yahiaelgayar/mall-dataset/mall_dataset/frames
  exists: True
MALL_GT_MAT: /kaggle/input/datasets/yahiaelgayar/mall-dataset/mall_dataset/mall_gt.mat
  exists: True
FIDTM_WEIGHT_PATH: /kaggle/input/datasets/yahiaelgayar/fidtm-model/model_best_jhu (1).pth
  exists: True
PET_WEIGHT_PATH: /kaggle/input/datasets/yahiaelgayar/pet-bestmodel/JHU_Crowd.pth
  exists: True
CLTR_WEIGHT_PATH: /kaggle/input/datasets/yahiaelgayar/cltr-model/video_model.pth
  exists: True
STEERER_WEIGHT_PATH: /kaggle/input/datasets/yahiaelgayar/steerer-models/JHU_mae_54.5_mse_240.6.pth
  exists: True

Benchmark output folder: /kaggle/working/benchmark_results

In [8]:
import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.io import loadmat

# -----------------------------
# Mall ground truth loader
# -----------------------------
def load_mall_samples(frames_dir: Path, gt_mat_path: Path) -> pd.DataFrame:
    """
    Load Mall dataset frame paths and ground-truth counts.

    Mall frames are named seq_000001.jpg, seq_000002.jpg, ...
    mall_gt.mat usually contains a 'count' array.
    """
    mat = loadmat(gt_mat_path)
    print("Mall .mat keys:", [k for k in mat.keys() if not k.startswith("__")])

    if "count" not in mat:
        raise KeyError("Could not find 'count' key in mall_gt.mat")

    counts = np.asarray(mat["count"]).reshape(-1)
    frame_paths = sorted(frames_dir.glob("*.jpg"))

    n = min(len(frame_paths), len(counts))

    rows = []
    for i in range(n):
        rows.append({
            "dataset": "Mall",
            "frame_id": frame_paths[i].stem,
            "image_path": str(frame_paths[i]),
            "gt_count": int(counts[i]),
        })

    return pd.DataFrame(rows)


# -----------------------------
# FDST ground truth loader
# -----------------------------
def count_points_in_fdst_json(json_path: Path) -> int:
    """
    Count annotated head points in one FDST JSON file.
    Handles common JSON structures safely.
    """
    with open(json_path, "r") as f:
        data = json.load(f)

    # Common FDST format: list of point dicts or dict containing points
    if isinstance(data, list):
        return len(data)

    if isinstance(data, dict):
        for key in ["points", "annotations", "annPoints", "gt_points", "locations"]:
            if key in data and isinstance(data[key], list):
                return len(data[key])

        # fallback: count values that look like point lists
        for value in data.values():
            if isinstance(value, list) and len(value) > 0:
                first = value[0]
                if isinstance(first, (list, tuple, dict)):
                    return len(value)

    raise ValueError(f"Unknown FDST JSON format: {json_path}")


def load_fdst_samples(images_dir: Path, jsons_dir: Path, max_frames: int = 6000) -> pd.DataFrame:
    """
    Load first max_frames FDST frames and ground-truth counts from matching JSON files.
    """
    image_paths = sorted(images_dir.glob("*.jpg"))[:max_frames]

    rows = []
    missing_json = 0

    for img_path in image_paths:
        json_path = jsons_dir / f"{img_path.stem}.json"

        if not json_path.exists():
            missing_json += 1
            continue

        gt_count = count_points_in_fdst_json(json_path)

        rows.append({
            "dataset": "FDST",
            "frame_id": img_path.stem,
            "image_path": str(img_path),
            "gt_count": int(gt_count),
        })

    if missing_json:
        print("Missing FDST JSON files:", missing_json)

    return pd.DataFrame(rows)


mall_df = load_mall_samples(MALL_FRAMES_DIR, MALL_GT_MAT)
fdst_df = load_fdst_samples(FDST_IMAGES_DIR, FDST_JSONS_DIR, MAX_FDST_FRAMES)

print("\nMall samples:", len(mall_df))
print(mall_df.head())
print(mall_df["gt_count"].describe())

print("\nFDST samples:", len(fdst_df))
print(fdst_df.head())
print(fdst_df["gt_count"].describe())

all_samples_df = pd.concat([mall_df, fdst_df], ignore_index=True)

samples_csv = BENCH_DIR / "benchmark_samples_mall_fdst_6000.csv"
all_samples_df.to_csv(samples_csv, index=False)

print("\nSaved samples CSV:", samples_csv)
print("Total samples:", len(all_samples_df))

Mall .mat keys: ['frame', 'count']

Mall samples: 2000
  dataset    frame_id                                         image_path  \
0    Mall  seq_000001  /kaggle/input/datasets/yahiaelgayar/mall-datas...
1    Mall  seq_000002  /kaggle/input/datasets/yahiaelgayar/mall-datas...
2    Mall  seq_000003  /kaggle/input/datasets/yahiaelgayar/mall-datas...
3    Mall  seq_000004  /kaggle/input/datasets/yahiaelgayar/mall-datas...
4    Mall  seq_000005  /kaggle/input/datasets/yahiaelgayar/mall-datas...

   gt_count
0        29
1        30
2        35
3        31
4        26
count    2000.000000
mean       31.157500
std         6.945417
min        13.000000
25%        26.000000
50%        31.000000
75%        36.000000
max        53.000000
Name: gt_count, dtype: float64

FDST samples: 6000
  dataset frame_id                                         image_path  \
0    FDST  100_001  /kaggle/input/datasets/yahiaelgayar/fdst-datas...
1    FDST  100_002  /kaggle/input/datasets/yahiaelgayar/fdst-datas...
2    FDST  100_003  /kaggle/input/datasets/yahiaelgayar/fdst-datas...
3    FDST  100_004  /kaggle/input/datasets/yahiaelgayar/fdst-datas...
4    FDST  100_005  /kaggle/input/datasets/yahiaelgayar/fdst-datas...

   gt_count
0        20
1        20
2        20
3        20
4        20
count    6000.000000
mean       21.252833
std         6.748296
min         9.000000
25%        16.000000
50%        21.000000
75%        26.000000
max        41.000000
Name: gt_count, dtype: float64

Saved samples CSV: /kaggle/working/benchmark_results/benchmark_samples_mall_fdst_6000.csv
Total samples: 8000

In [9]:
import subprocess
from pathlib import Path

REPOS_DIR = WORK_DIR / "repos"
REPOS_DIR.mkdir(parents=True, exist_ok=True)

REPO_URLS = {
    "FIDTM": "https://github.com/Serendipity-55428/FIDTM.git",
    "PET": "https://github.com/cxliu0/PET.git",
    "CLTR": "https://github.com/Verg-Avesta/Crowd_counting_from_scratch.git",
    "STEERER": "https://github.com/taohan10200/STEERER.git",
}

def clone_repo(name: str, url: str, target_dir: Path) -> None:
    if target_dir.exists():
        print(f"{name} already exists:", target_dir)
        return

    print(f"Cloning {name}...")
    result = subprocess.run(
        ["git", "clone", url, str(target_dir)],
        text=True,
        capture_output=True,
    )

    if result.returncode != 0:
        print(f"FAILED cloning {name}")
        print(result.stderr)
    else:
        print(f"Cloned {name}:", target_dir)

for name, url in REPO_URLS.items():
    clone_repo(name, url, REPOS_DIR / name)

print("\nRepos folder:")
for p in sorted(REPOS_DIR.iterdir()):
    print(" -", p)

Cloning FIDTM...
FAILED cloning FIDTM
Cloning into '/kaggle/working/repos/FIDTM'...
fatal: could not read Username for 'https://github.com': No such device or address

Cloning PET...
Cloned PET: /kaggle/working/repos/PET
Cloning CLTR...
FAILED cloning CLTR
Cloning into '/kaggle/working/repos/CLTR'...
fatal: could not read Username for 'https://github.com': No such device or address

Cloning STEERER...
Cloned STEERER: /kaggle/working/repos/STEERER

Repos folder:
 - /kaggle/working/repos/PET
 - /kaggle/working/repos/STEERER

In [10]:
import shutil
import subprocess
from pathlib import Path

REPOS_DIR = WORK_DIR / "repos"
REPOS_DIR.mkdir(parents=True, exist_ok=True)

REPO_URLS = {
    "FIDTM": "https://github.com/dk-liang/FIDTM.git",
    "PET": "https://github.com/cxliu0/PET.git",
    "CLTR": "https://github.com/dk-liang/CLTR.git",
    "STEERER": "https://github.com/taohan10200/STEERER.git",
}

def clone_or_refresh_repo(name: str, url: str, target_dir: Path) -> None:
    if target_dir.exists():
        print(f"{name} already exists:", target_dir)
        return

    print(f"Cloning {name} from {url}")
    result = subprocess.run(
        ["git", "clone", url, str(target_dir)],
        text=True,
        capture_output=True,
    )

    if result.returncode != 0:
        print(f"FAILED cloning {name}")
        print(result.stderr)
    else:
        print(f"Cloned {name}:", target_dir)

for name, url in REPO_URLS.items():
    clone_or_refresh_repo(name, url, REPOS_DIR / name)

print("\nRepos now available:")
for p in sorted(REPOS_DIR.iterdir()):
    print(" -", p)

Cloning FIDTM from https://github.com/dk-liang/FIDTM.git
Cloned FIDTM: /kaggle/working/repos/FIDTM
PET already exists: /kaggle/working/repos/PET
Cloning CLTR from https://github.com/dk-liang/CLTR.git
Cloned CLTR: /kaggle/working/repos/CLTR
STEERER already exists: /kaggle/working/repos/STEERER

Repos now available:
 - /kaggle/working/repos/CLTR
 - /kaggle/working/repos/FIDTM
 - /kaggle/working/repos/PET
 - /kaggle/working/repos/STEERER

In [11]:
from pathlib import Path

def show_tree_limited(root: Path, max_depth: int = 3, max_items: int = 40):
    print(f"\nROOT: {root}")
    if not root.exists():
        print("Missing")
        return

    def _walk(path: Path, depth: int, prefix: str):
        if depth > max_depth:
            return

        items = sorted(list(path.iterdir()), key=lambda x: (x.is_file(), x.name.lower()))
        shown = items[:max_items]

        for item in shown:
            if item.is_dir():
                print(prefix + f"[DIR]  {item.name}")
                _walk(item, depth + 1, prefix + "  ")
            else:
                print(prefix + f"[FILE] {item.name}")

        if len(items) > max_items:
            print(prefix + f"... {len(items) - max_items} more items not shown")

    _walk(root, 1, "")


for repo_name in ["FIDTM", "PET", "CLTR", "STEERER"]:
    show_tree_limited(REPOS_DIR / repo_name, max_depth=3, max_items=30)

ROOT: /kaggle/working/repos/FIDTM
[DIR]  .git
  [DIR]  branches
  [DIR]  hooks
    [FILE] applypatch-msg.sample
    [FILE] commit-msg.sample
    [FILE] fsmonitor-watchman.sample
    [FILE] post-update.sample
    [FILE] pre-applypatch.sample
    [FILE] pre-commit.sample
    [FILE] pre-merge-commit.sample
    [FILE] pre-push.sample
    [FILE] pre-rebase.sample
    [FILE] pre-receive.sample
    [FILE] prepare-commit-msg.sample
    [FILE] push-to-checkout.sample
    [FILE] update.sample
  [DIR]  info
    [FILE] exclude
  [DIR]  logs
    [DIR]  refs
    [FILE] HEAD
  [DIR]  objects
    [DIR]  info
    [DIR]  pack
  [DIR]  refs
    [DIR]  heads
    [DIR]  remotes
    [DIR]  tags
  [FILE] config
  [FILE] description
  [FILE] HEAD
  [FILE] index
  [FILE] packed-refs
[DIR]  data
  [FILE] fidt_generate_jhu.py
  [FILE] fidt_generate_qnrf.py
  [FILE] fidt_generate_sh.py
[DIR]  image
  [FILE] .DS_Store
  [FILE] bounding_boxes.jpeg
  [FILE] demo.jpeg
  [FILE] fidtmap.png
  [FILE] overview.png
[DIR]  local_eval
  [DIR]  point_files
    [FILE] A_gt.txt
    [FILE] A_pred_fidt.txt
    [FILE] B_gt.txt
    [FILE] B_pred_fidt.txt
    [FILE] jhu_gt.txt
    [FILE] jhu_pred_fidt.txt
    [FILE] nwpu_gt (val set).txt
    [FILE] nwpu_pred_fidt (val set).txt
    [FILE] nwpu_pred_fidt.txt
    [FILE] qnrf_pred_fidt.txt
  [FILE] .DS_Store
  [FILE] eval.py
  [FILE] eval_qnrf.py
  [FILE] gt_generate.py
  [FILE] utils.py
  [FILE] vis4val.py
[DIR]  Networks
  [DIR]  HR_Net
    [FILE] __init__.py
    [FILE] config.py
    [FILE] default.py
    [FILE] models.py
    [FILE] seg_hrnet.py
    [FILE] seg_hrnet_w48.yaml
[FILE] .DS_Store
[FILE] config.py
[FILE] dataset.py
[FILE] image.py
[FILE] LICENSE
[FILE] make_npydata.py
[FILE] README.md
[FILE] test.py
[FILE] train_baseline.py
[FILE] utils.py
[FILE] video_demo.py

ROOT: /kaggle/working/repos/PET
[DIR]  .git
  [DIR]  branches
  [DIR]  hooks
    [FILE] applypatch-msg.sample
    [FILE] commit-msg.sample
    [FILE] fsmonitor-watchman.sample
    [FILE] post-update.sample
    [FILE] pre-applypatch.sample
    [FILE] pre-commit.sample
    [FILE] pre-merge-commit.sample
    [FILE] pre-push.sample
    [FILE] pre-rebase.sample
    [FILE] pre-receive.sample
    [FILE] prepare-commit-msg.sample
    [FILE] push-to-checkout.sample
    [FILE] update.sample
  [DIR]  info
    [FILE] exclude
  [DIR]  logs
    [DIR]  refs
    [FILE] HEAD
  [DIR]  objects
    [DIR]  info
    [DIR]  pack
  [DIR]  refs
    [DIR]  heads
    [DIR]  remotes
    [DIR]  tags
  [FILE] config
  [FILE] description
  [FILE] HEAD
  [FILE] index
  [FILE] packed-refs
[DIR]  datasets
  [FILE] __init__.py
  [FILE] SHA.py
[DIR]  models
  [DIR]  backbones
    [FILE] __init__.py
    [FILE] backbone_vgg.py
    [FILE] vgg.py
  [DIR]  transformer
    [FILE] __init__.py
    [FILE] prog_win_transformer.py
    [FILE] utils.py
  [FILE] __init__.py
  [FILE] matcher.py
  [FILE] pet.py
  [FILE] position_encoding.py
[DIR]  util
  [FILE] __init__.py
  [FILE] misc.py
[FILE] .gitignore
[FILE] engine.py
[FILE] eval.py
[FILE] eval.sh
[FILE] LICENSE
[FILE] main.py
[FILE] preprocess_dataset.py
[FILE] README.md
[FILE] requirements.txt
[FILE] teaser.JPG
[FILE] test_single_image.py
[FILE] train.sh

ROOT: /kaggle/working/repos/CLTR
[DIR]  .git
  [DIR]  branches
  [DIR]  hooks
    [FILE] applypatch-msg.sample
    [FILE] commit-msg.sample
    [FILE] fsmonitor-watchman.sample
    [FILE] post-update.sample
    [FILE] pre-applypatch.sample
    [FILE] pre-commit.sample
    [FILE] pre-merge-commit.sample
    [FILE] pre-push.sample
    [FILE] pre-rebase.sample
    [FILE] pre-receive.sample
    [FILE] prepare-commit-msg.sample
    [FILE] push-to-checkout.sample
    [FILE] update.sample
  [DIR]  info
    [FILE] exclude
  [DIR]  logs
    [DIR]  refs
    [FILE] HEAD
  [DIR]  objects
    [DIR]  info
    [DIR]  pack
  [DIR]  refs
    [DIR]  heads
    [DIR]  remotes
    [DIR]  tags
  [FILE] config
  [FILE] description
  [FILE] HEAD
  [FILE] index
  [FILE] packed-refs
[DIR]  data
  [DIR]  NWPU_list
    [FILE] test.txt
    [FILE] train.txt
    [FILE] val.txt
  [FILE] .DS_Store
  [FILE] prepare_jhu.py
  [FILE] prepare_nwpu.py
[DIR]  experiments
  [FILE] jhu.sh
  [FILE] nwpu.sh
[DIR]  images
  [FILE] .DS_Store
  [FILE] intro.jpeg
  [FILE] NWPU.log
[DIR]  Networks
  [DIR]  CDETR
    [FILE] __init__.py
    [FILE] attention.py
    [FILE] backbone.py
    [FILE] conditional_detr.py
    [FILE] matcher.py
    [FILE] position_encoding.py
    [FILE] segmentation.py
    [FILE] transformer.py
[DIR]  util
  [FILE] __init__.py
  [FILE] box_ops.py
  [FILE] misc.py
[DIR]  video_demo
  [FILE] demo.mp4
[FILE] config.py
[FILE] dataset.py
[FILE] image.py
[FILE] LICENSE
[FILE] make_npydata.py
[FILE] README.md
[FILE] test.py
[FILE] train_distributed.py
[FILE] utils.py
[FILE] video_demo.py

ROOT: /kaggle/working/repos/STEERER
[DIR]  .git
  [DIR]  branches
  [DIR]  hooks
    [FILE] applypatch-msg.sample
    [FILE] commit-msg.sample
    [FILE] fsmonitor-watchman.sample
    [FILE] post-update.sample
    [FILE] pre-applypatch.sample
    [FILE] pre-commit.sample
    [FILE] pre-merge-commit.sample
    [FILE] pre-push.sample
    [FILE] pre-rebase.sample
    [FILE] pre-receive.sample
    [FILE] prepare-commit-msg.sample
    [FILE] push-to-checkout.sample
    [FILE] update.sample
  [DIR]  info
    [FILE] exclude
  [DIR]  logs
    [DIR]  refs
    [FILE] HEAD
  [DIR]  objects
    [DIR]  info
    [DIR]  pack
  [DIR]  refs
    [DIR]  heads
    [DIR]  remotes
    [DIR]  tags
  [FILE] config
  [FILE] description
  [FILE] HEAD
  [FILE] index
  [FILE] packed-refs
[DIR]  configs
  [DIR]  ablation
    [FILE] NWPU_HR_base_concat.py
    [FILE] NWPU_HR_base_fpn.py
    [FILE] QNRF_HR_4096_2048_fpn.py
    [FILE] QNRF_HR_4096_2048_ps128.py
    [FILE] QNRF_HR_4096_2048_ps192.py
    [FILE] QNRF_HR_4096_2048_ps320.py
    [FILE] SHHA_HR_3branch.py
    [FILE] SHHA_HR_base_0_1_2_loss.py
    [FILE] SHHA_HR_base_0_1_loss.py
    [FILE] SHHA_HR_base_0_loss.py
    [FILE] SHHA_HR_base_4full_loss.py
    [FILE] SHHA_HR_base_4self_loss.py
    [FILE] SHHA_HR_base_concat.py
    [FILE] SHHA_HR_base_fpn.py
    [FILE] SHHA_HR_base_nohead_share.py
    [FILE] SHHA_HR_base_SFN.py
    [FILE] SHHA_HR_base_SFN_UFN.py
    [FILE] SHHB_HR_base_fpn.py
  [DIR]  HRNet
    [FILE] NWPU_HR.py
    [FILE] QNRF_HR.py
    [FILE] QNRF_HR_baseline.py
    [FILE] SHHA_HR_base.py
    [FILE] SHHA_HR_baseline.py
    [FILE] SHHB_HR.py
  [DIR]  VGG
    [FILE] FDST_vgg19_bn.py
    [FILE] JHU_vgg19_bn.py
    [FILE] NWPU_vgg19_2048.py
    [FILE] NWPU_vgg19_4096.py
    [FILE] QNRF_vgg19_bn.py
    [FILE] QNRF_vgg19_bn_baseline.py
    [FILE] SHHA_vgg19_bn.py
    [FILE] SHHA_vgg19_bn_baseline.py
    [FILE] SHHB_vgg19_bn.py
    [FILE] SHHB_vgg19_bn_baseline.py
    [FILE] SHHBx2_vgg19.py
  [DIR]  VIT
    [FILE] QNRF_vit.py
    [FILE] SHHA_vit.py
    [FILE] SHHA_vit_large.py
    [FILE] SHHB_clip.py
    [FILE] SHHB_vit.py
    [FILE] SHHB_vit_large.py
  [FILE] FDST_final.py
  [FILE] JHU_final.py
  [FILE] MTC_final.py
  [FILE] NWPU_2048_HR.py
  [FILE] NWPU_2048_HR_200.py
  [FILE] NWPU_final.py
  [FILE] NWPU_HR.py
  [FILE] NWPU_HR_full_5120.py
  [FILE] NWPU_HRT_2048_2048.py
  [FILE] QNRF_final.py
  [FILE] SHHA_final.py
  [FILE] SHHB_final.py
  [FILE] TRANCOS_final.py
  [FILE] TREE_HR_final.py
[DIR]  figures
  [FILE] framework.png
[DIR]  lib
  [DIR]  __pycache__
    [FILE] __init__.cpython-310.pyc
    [FILE] __init__.cpython-38.pyc
    [FILE] __init__.cpython-39.pyc
  [DIR]  config
    [DIR]  __pycache__
    [FILE] __init__.py
    [FILE] default.py
    [FILE] models.py
  [DIR]  core
    [DIR]  __pycache__
    [FILE] cc_function.py
    [FILE] Counter.py
    [FILE] criterion.py
    [FILE] evaluate.py
    [FILE] function.py
  [DIR]  datasets
    [DIR]  __pycache__
    [DIR]  prepare
    [DIR]  utils
    [FILE] __init__.py
    [FILE] base_dataset.py
    [FILE] fdst.py
    [FILE] jhu.py
    [FILE] mtc.py
    [FILE] nwpu.py
    [FILE] qnrf.py
    [FILE] shha.py
    [FILE] shhb.py
    [FILE] trancos.py
    [FILE] urban_tree.py
  [DIR]  eval
    [DIR]  __pycache__
    [FILE] __init__.py
    [FILE] compute_metric.py
    [FILE] eval_det.py
    [FILE] eval_loc_count.py
    [FILE] JHU_test_gt_loc.txt
    [FILE] QNRF_test_gt_loc.txt
    [FILE] SHHA_test_gt_loc.txt
    [FILE] SHHB_test_gt_loc.txt
    [FILE] SHHB_test_loc.txt
    [FILE] SHHB_test_pre_loc.txt
    [FILE] utils.py
    [FILE] vis4val.py
  [DIR]  models
    [DIR]  __pycache__
    [DIR]  backbones
    [DIR]  heads
    [DIR]  layers
    [FILE] __init__.py
    [FILE] base_backbone.py
    [FILE] build_counter.py
    [FILE] internet.py
    [FILE] internet_drcounter.py
    [FILE] seg_hrnet.py
    [FILE] seg_hrnet_down.py
    [FILE] seg_hrnet_drcounter.py
    [FILE] seg_hrnet_sum.py
    [FILE] VGG16_FPN.py
    [FILE] vit.py
  [DIR]  solver
    [DIR]  __pycache__
    [FILE] __init__.py
    [FILE] build.py
    [FILE] lr_scheduler.py
    [FILE] lr_scheduler_cls.py
  [DIR]  utils
    [DIR]  __pycache__
    [FILE] __init__.py
    [FILE] dist_utils.py
    [FILE] flop_count.py
    [FILE] Gaussianlayer.py
    [FILE] get_bbox.py
    [FILE] jit_handles.py
    [FILE] KPI_pool.py
    [FILE] logger.py
    [FILE] metric.py
    [FILE] modelsummary.py
    [FILE] nmc.py
    [FILE] points_from_den.py
    [FILE] utils.py
  [FILE] __init__.py
  [FILE] builder.py
[DIR]  scale_generalization
  [DIR]  __pycache__
    [FILE] _init_paths.cpython-38.pyc
  [DIR]  autoscale
    [DIR]  __pycache__
    [FILE] find_couter.py
    [FILE] fpn.py
    [FILE] NWPU_HR_autoscale.py
    [FILE] rate_model.py
    [FILE] utils.py
  [FILE] _init_paths.py
  [FILE] eventSHHB.py
  [FILE] figure.py
  [FILE] read_TorchEvents.py
  [FILE] test_autoscale.py
  [FILE] test_scale_level.py
[DIR]  tools
  [DIR]  __pycache__
    [FILE] _init_paths.cpython-310.pyc
    [FILE] _init_paths.cpython-35.pyc
    [FILE] _init_paths.cpython-36.pyc
    [FILE] _init_paths.cpython-37.pyc
    [FILE] _init_paths.cpython-38.pyc
    [FILE] _init_paths.cpython-39.pyc
  [FILE] _init_paths.py
  [FILE] model_test.py
  [FILE] test_cc.py
  [FILE] test_loc.py
  [FILE] test_single_img.py
  [FILE] train_cc.py
[FILE] .gitignore
[FILE] cam.py
[FILE] feature_vis.py
[FILE] LICENSE
[FILE] README.md
[FILE] requirements.txt
[FILE] slurm_test.sh
[FILE] slurm_train.sh
[FILE] test.sh
[FILE] train.sh

In [12]:
import torch

CHECKPOINTS = {
    "FIDTM": FIDTM_WEIGHT_PATH,
    "PET": PET_WEIGHT_PATH,
    "CLTR": CLTR_WEIGHT_PATH,
    "STEERER": STEERER_WEIGHT_PATH
}

for name, path in CHECKPOINTS.items():

    print("\n" + "="*80)
    print(name)
    print("="*80)

    ckpt = torch.load(path, map_location="cpu")

    print("Type:", type(ckpt))

    if isinstance(ckpt, dict):
        print("Top keys:")

        for k in list(ckpt.keys())[:20]:
            print("-", k)

        if "state_dict" in ckpt:
            print("\nstate_dict keys sample:")

            sd = ckpt["state_dict"]

            for k in list(sd.keys())[:20]:
                print(" ",k)

        elif "model" in ckpt:
            print("\nmodel keys sample:")

            sd = ckpt["model"]

            if isinstance(sd,dict):
                for k in list(sd.keys())[:20]:
                    print(" ",k)

    print()

================================================================================
FIDTM
================================================================================
Type: <class 'dict'>
Top keys:
- epoch
- arch
- state_dict
- best_prec1
- optimizer

state_dict keys sample:
  module.conv1.weight
  module.bn1.weight
  module.bn1.bias
  module.bn1.running_mean
  module.bn1.running_var
  module.bn1.num_batches_tracked
  module.conv2.weight
  module.bn2.weight
  module.bn2.bias
  module.bn2.running_mean
  module.bn2.running_var
  module.bn2.num_batches_tracked
  module.layer1.0.conv1.weight
  module.layer1.0.bn1.weight
  module.layer1.0.bn1.bias
  module.layer1.0.bn1.running_mean
  module.layer1.0.bn1.running_var
  module.layer1.0.bn1.num_batches_tracked
  module.layer1.0.conv2.weight
  module.layer1.0.bn2.weight


================================================================================
PET
================================================================================
Type: <class 'dict'>
Top keys:
- model

model keys sample:
  backbone.0.body1.0.weight
  backbone.0.body1.0.bias
  backbone.0.body1.1.weight
  backbone.0.body1.1.bias
  backbone.0.body1.1.running_mean
  backbone.0.body1.1.running_var
  backbone.0.body1.1.num_batches_tracked
  backbone.0.body1.3.weight
  backbone.0.body1.3.bias
  backbone.0.body1.4.weight
  backbone.0.body1.4.bias
  backbone.0.body1.4.running_mean
  backbone.0.body1.4.running_var
  backbone.0.body1.4.num_batches_tracked
  backbone.0.body1.7.weight
  backbone.0.body1.7.bias
  backbone.0.body1.8.weight
  backbone.0.body1.8.bias
  backbone.0.body1.8.running_mean
  backbone.0.body1.8.running_var


================================================================================
CLTR
================================================================================
Type: <class 'dict'>
Top keys:
- epoch
- arch
- state_dict
- best_prec1
- optimizer

state_dict keys sample:
  module.transformer.encoder.layers.0.self_attn.in_proj_weight
  module.transformer.encoder.layers.0.self_attn.in_proj_bias
  module.transformer.encoder.layers.0.self_attn.out_proj.weight
  module.transformer.encoder.layers.0.self_attn.out_proj.bias
  module.transformer.encoder.layers.0.linear1.weight
  module.transformer.encoder.layers.0.linear1.bias
  module.transformer.encoder.layers.0.linear2.weight
  module.transformer.encoder.layers.0.linear2.bias
  module.transformer.encoder.layers.0.norm1.weight
  module.transformer.encoder.layers.0.norm1.bias
  module.transformer.encoder.layers.0.norm2.weight
  module.transformer.encoder.layers.0.norm2.bias
  module.transformer.encoder.layers.1.self_attn.in_proj_weight
  module.transformer.encoder.layers.1.self_attn.in_proj_bias
  module.transformer.encoder.layers.1.self_attn.out_proj.weight
  module.transformer.encoder.layers.1.self_attn.out_proj.bias
  module.transformer.encoder.layers.1.linear1.weight
  module.transformer.encoder.layers.1.linear1.bias
  module.transformer.encoder.layers.1.linear2.weight
  module.transformer.encoder.layers.1.linear2.bias


================================================================================
STEERER
================================================================================
Type: <class 'collections.OrderedDict'>
Top keys:
- backbone.conv1.weight
- backbone.bn1.weight
- backbone.bn1.bias
- backbone.bn1.running_mean
- backbone.bn1.running_var
- backbone.bn1.num_batches_tracked
- backbone.conv2.weight
- backbone.bn2.weight
- backbone.bn2.bias
- backbone.bn2.running_mean
- backbone.bn2.running_var
- backbone.bn2.num_batches_tracked
- backbone.layer1.0.conv1.weight
- backbone.layer1.0.bn1.weight
- backbone.layer1.0.bn1.bias
- backbone.layer1.0.bn1.running_mean
- backbone.layer1.0.bn1.running_var
- backbone.layer1.0.bn1.num_batches_tracked
- backbone.layer1.0.conv2.weight
- backbone.layer1.0.bn2.weight

In [13]:
import importlib.util
import subprocess
import sys

packages = {
    "easydict": "easydict",
    "timm": "timm",
    "einops": "einops",
    "scipy": "scipy",
    "matplotlib": "matplotlib",
}

missing = []

for import_name, pip_name in packages.items():
    if importlib.util.find_spec(import_name) is None:
        missing.append(pip_name)

print("Missing packages:", missing)

if missing:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q"] + missing)

print("Dependency check complete.")

Missing packages: []
Dependency check complete.

In [14]:
import sys
import numpy as np
from pathlib import Path

# Some older repos use deprecated NumPy aliases.
np.float = float
np.int = int
np.bool = bool

REPO_PATHS = {
    "FIDTM": REPOS_DIR / "FIDTM",
    "PET": REPOS_DIR / "PET",
    "CLTR": REPOS_DIR / "CLTR",
    "STEERER": REPOS_DIR / "STEERER",
}

for name, path in REPO_PATHS.items():
    path_str = str(path)
    if path_str not in sys.path:
        sys.path.insert(0, path_str)
    print(name, "added:", path)

print("\nPython path ready.")

FIDTM added: /kaggle/working/repos/FIDTM
PET added: /kaggle/working/repos/PET
CLTR added: /kaggle/working/repos/CLTR
STEERER added: /kaggle/working/repos/STEERER

Python path ready.

In [16]:
import sys
import subprocess

subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "yacs"])

print("Installed yacs.")

Installed yacs.

In [17]:
import os
import sys
import torch
import torch.nn as nn
from pathlib import Path

FIDTM_REPO = REPOS_DIR / "FIDTM"
os.chdir(FIDTM_REPO)

if str(FIDTM_REPO) not in sys.path:
    sys.path.insert(0, str(FIDTM_REPO))

from Networks.HR_Net.seg_hrnet import get_seg_model

fidtm_model = get_seg_model()
fidtm_model = nn.DataParallel(fidtm_model)

fidtm_ckpt = torch.load(FIDTM_WEIGHT_PATH, map_location="cpu")
fidtm_state = fidtm_ckpt["state_dict"]

missing, unexpected = fidtm_model.load_state_dict(fidtm_state, strict=False)

fidtm_model = fidtm_model.to(DEVICE)
fidtm_model.eval()

print("FIDTM loaded.")
print("Missing keys:", len(missing))
print("Unexpected keys:", len(unexpected))
print("Device:", DEVICE)

FIDTM loaded.
Missing keys: 0
Unexpected keys: 0
Device: cuda

In [18]:
import cv2
import time
import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image
from torchvision import transforms

FIDTM_MEAN = [0.485, 0.456, 0.406]
FIDTM_STD = [0.229, 0.224, 0.225]

fidtm_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=FIDTM_MEAN, std=FIDTM_STD),
])

def resize_to_multiple_of_16(image_rgb: np.ndarray):
    h, w = image_rgb.shape[:2]
    new_h = h - (h % 16)
    new_w = w - (w % 16)

    if new_h <= 0 or new_w <= 0:
        raise ValueError(f"Invalid resized shape from {image_rgb.shape}")

    resized = cv2.resize(image_rgb, (new_w, new_h), interpolation=cv2.INTER_LINEAR)
    return resized, (h, w), (new_h, new_w)


@torch.no_grad()
def predict_fidtm_count(image_path: str):
    """
    Returns:
        pred_count: float
        inference_time: seconds
    """
    bgr = cv2.imread(image_path)
    if bgr is None:
        raise FileNotFoundError(image_path)

    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    rgb_resized, original_shape, resized_shape = resize_to_multiple_of_16(rgb)

    x = fidtm_transform(Image.fromarray(rgb_resized)).unsqueeze(0).to(DEVICE)

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    start = time.perf_counter()
    output = fidtm_model(x)

    if isinstance(output, (list, tuple)):
        output = output[0]

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    elapsed = time.perf_counter() - start

    pred_count = float(output.detach().sum().item())

    return pred_count, elapsed


sample_row = mall_df.iloc[0]
pred, sec = predict_fidtm_count(sample_row["image_path"])

print("Sample:", sample_row["image_path"])
print("GT count:", sample_row["gt_count"])
print("FIDTM pred:", pred)
print("Inference time:", sec)
print("FPS:", 1.0 / sec if sec > 0 else None)

Sample: /kaggle/input/datasets/yahiaelgayar/mall-dataset/mall_dataset/frames/seq_000001.jpg
GT count: 29
FIDTM pred: 4133.5126953125
Inference time: 2.0840964690000874
FPS: 0.4798242379249279

/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:454: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x1 = F.upsample(x[1], size=(x0_h, x0_w), mode='bilinear')
/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:455: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x2 = F.upsample(x[2], size=(x0_h, x0_w), mode='bilinear')
/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:456: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x3 = F.upsample(x[3], size=(x0_h, x0_w), mode='bilinear')

In [19]:
@torch.no_grad()
def inspect_fidtm_output(image_path: str):
    bgr = cv2.imread(image_path)
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    rgb_resized, _, _ = resize_to_multiple_of_16(rgb)

    x = fidtm_transform(Image.fromarray(rgb_resized)).unsqueeze(0).to(DEVICE)

    output = fidtm_model(x)

    print("Output type:", type(output))

    if isinstance(output, (list, tuple)):
        print("Output length:", len(output))
        for i, o in enumerate(output):
            print(f"output[{i}] shape:", o.shape)
            print(" min:", float(o.min()), "max:", float(o.max()), "sum:", float(o.sum()), "mean:", float(o.mean()))
    else:
        print("Output shape:", output.shape)
        print("min:", float(output.min()))
        print("max:", float(output.max()))
        print("sum:", float(output.sum()))
        print("mean:", float(output.mean()))

inspect_fidtm_output(mall_df.iloc[0]["image_path"])

Output type: <class 'torch.Tensor'>
Output shape: torch.Size([1, 1, 480, 640])
min: -0.009754583239555359
max: 0.482133686542511
sum: 4133.5126953125
mean: 0.013455444946885109

In [20]:
import cv2
import numpy as np
import torch
from PIL import Image

def extract_points_from_fidtm_map(
    pred_map: np.ndarray,
    threshold: float = 0.10,
    nms_kernel: int = 15,
):
    """
    Convert FIDTM response map into predicted head points using local maxima.

    Returns:
        List of (x, y, score)
    """
    pred_map = np.squeeze(pred_map)

    if pred_map.ndim != 2:
        raise ValueError(f"Expected 2D map, got shape {pred_map.shape}")

    # Remove negative values
    pred_map = np.maximum(pred_map, 0)

    # Local max filter
    kernel = np.ones((nms_kernel, nms_kernel), np.uint8)
    local_max = cv2.dilate(pred_map, kernel)

    peaks = (pred_map == local_max) & (pred_map >= threshold)

    ys, xs = np.where(peaks)

    points = []
    for x, y in zip(xs, ys):
        points.append((float(x), float(y), float(pred_map[y, x])))

    return points


@torch.no_grad()
def predict_fidtm_points(image_path: str, threshold: float = 0.10, nms_kernel: int = 15):
    """
    Predict FIDTM head points and count.
    """
    bgr = cv2.imread(image_path)
    if bgr is None:
        raise FileNotFoundError(image_path)

    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    rgb_resized, original_shape, resized_shape = resize_to_multiple_of_16(rgb)

    x = fidtm_transform(Image.fromarray(rgb_resized)).unsqueeze(0).to(DEVICE)

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    start = time.perf_counter()
    output = fidtm_model(x)

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    elapsed = time.perf_counter() - start

    pred_map = output.squeeze().detach().cpu().numpy()

    points = extract_points_from_fidtm_map(
        pred_map,
        threshold=threshold,
        nms_kernel=nms_kernel,
    )

    return {
        "count": len(points),
        "points": points,
        "time_sec": elapsed,
        "map_shape": pred_map.shape,
    }


sample_row = mall_df.iloc[0]

for th in [0.03, 0.05, 0.07, 0.10, 0.15, 0.20]:
    result = predict_fidtm_points(sample_row["image_path"], threshold=th, nms_kernel=15)
    print(f"threshold={th:.2f} | pred_count={result['count']} | gt={sample_row['gt_count']} | time={result['time_sec']:.4f}s")

threshold=0.03 | pred_count=42 | gt=29 | time=0.1677s
threshold=0.05 | pred_count=40 | gt=29 | time=0.1361s
threshold=0.07 | pred_count=39 | gt=29 | time=0.1232s
threshold=0.10 | pred_count=39 | gt=29 | time=0.1131s
threshold=0.15 | pred_count=37 | gt=29 | time=0.1083s
threshold=0.20 | pred_count=33 | gt=29 | time=0.1034s

In [21]:
from tqdm.auto import tqdm
import numpy as np
import pandas as pd

FIDTM_THRESHOLD = 0.20
FIDTM_NMS_KERNEL = 15

def compute_count_metrics(gt_counts, pred_counts):
    gt = np.array(gt_counts, dtype=np.float32)
    pred = np.array(pred_counts, dtype=np.float32)

    errors = np.abs(pred - gt)
    sq_errors = (pred - gt) ** 2

    mae = float(np.mean(errors))
    rmse = float(np.sqrt(np.mean(sq_errors)))

    return mae, rmse


def run_fidtm_count_benchmark(samples_df: pd.DataFrame, max_samples: int = None):
    rows = []

    if max_samples is not None:
        samples_df = samples_df.head(max_samples).copy()

    for _, row in tqdm(samples_df.iterrows(), total=len(samples_df)):
        result = predict_fidtm_points(
            row["image_path"],
            threshold=FIDTM_THRESHOLD,
            nms_kernel=FIDTM_NMS_KERNEL,
        )

        rows.append({
            "model": "FIDTM",
            "dataset": row["dataset"],
            "frame_id": row["frame_id"],
            "image_path": row["image_path"],
            "gt_count": int(row["gt_count"]),
            "pred_count": int(result["count"]),
            "abs_error": abs(int(result["count"]) - int(row["gt_count"])),
            "sq_error": (int(result["count"]) - int(row["gt_count"])) ** 2,
            "time_sec": float(result["time_sec"]),
            "fps": float(1.0 / result["time_sec"]) if result["time_sec"] > 0 else 0.0,
            "num_pred_points": len(result["points"]),
        })

    return pd.DataFrame(rows)


quick_samples = pd.concat([
    mall_df.head(100),
    fdst_df.head(100),
], ignore_index=True)

fidtm_quick_df = run_fidtm_count_benchmark(quick_samples)

display(fidtm_quick_df.head())

quick_summary = (
    fidtm_quick_df
    .groupby(["model", "dataset"])
    .agg(
        frames=("frame_id", "count"),
        mae=("abs_error", "mean"),
        rmse=("sq_error", lambda x: float(np.sqrt(np.mean(x)))),
        avg_fps=("fps", "mean"),
        avg_time_sec=("time_sec", "mean"),
        mean_gt=("gt_count", "mean"),
        mean_pred=("pred_count", "mean"),
    )
    .reset_index()
)

display(quick_summary)

  0%|          | 0/200 [00:00<?, ?it/s]

/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:454: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x1 = F.upsample(x[1], size=(x0_h, x0_w), mode='bilinear')
/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:455: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x2 = F.upsample(x[2], size=(x0_h, x0_w), mode='bilinear')
/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:456: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x3 = F.upsample(x[3], size=(x0_h, x0_w), mode='bilinear')

,model,dataset,frame_id,image_path,gt_count,pred_count,abs_error,sq_error,time_sec,fps,num_pred_points
0,FIDTM,Mall,seq_000001,/kaggle/input/datasets/yahiaelgayar/mall-datas...,29,33,4,16,0.168217,5.944714,33
1,FIDTM,Mall,seq_000002,/kaggle/input/datasets/yahiaelgayar/mall-datas...,30,29,1,1,0.169311,5.906288,29
2,FIDTM,Mall,seq_000003,/kaggle/input/datasets/yahiaelgayar/mall-datas...,35,34,1,1,0.118336,8.450531,34
3,FIDTM,Mall,seq_000004,/kaggle/input/datasets/yahiaelgayar/mall-datas...,31,32,1,1,0.103428,9.668547,32
4,FIDTM,Mall,seq_000005,/kaggle/input/datasets/yahiaelgayar/mall-datas...,26,26,0,0,0.103670,9.646035,26

,model,dataset,frames,mae,rmse,avg_fps,avg_time_sec,mean_gt,mean_pred
0,FIDTM,FDST,100,3.86,4.349713,1.879803,0.533250,21.89,25.67
1,FIDTM,Mall,100,2.02,2.687006,9.343481,0.108784,26.08,25.86

In [22]:
import json
import numpy as np
from scipy.io import loadmat

def load_mall_gt_points_map(gt_mat_path: Path):
    """
    Load Mall ground-truth point locations from mall_gt.mat.

    Returns:
        dict: frame_id -> list[(x, y)]
    """
    mat = loadmat(gt_mat_path)
    frame_data = mat["frame"]

    gt_map = {}

    for i in range(frame_data.shape[1]):
        frame_id = f"seq_{i+1:06d}"

        entry = frame_data[0, i]

        # Mall stores location points inside nested MATLAB structures.
        points = None

        def find_points(obj):
            if isinstance(obj, np.ndarray):
                if obj.ndim == 2 and obj.shape[1] == 2 and np.issubdtype(obj.dtype, np.number):
                    return obj
                for item in obj.flat:
                    found = find_points(item)
                    if found is not None:
                        return found
            return None

        points = find_points(entry)

        if points is None:
            gt_map[frame_id] = []
        else:
            gt_map[frame_id] = [(float(x), float(y)) for x, y in points]

    return gt_map


def load_fdst_points_from_json(json_path: Path):
    """
    Load FDST GT point locations from JSON.
    Returns list[(x, y)].
    """
    with open(json_path, "r") as f:
        data = json.load(f)

    points = []

    if isinstance(data, list):
        raw_points = data
    elif isinstance(data, dict):
        raw_points = None
        for key in ["points", "annotations", "annPoints", "gt_points", "locations"]:
            if key in data and isinstance(data[key], list):
                raw_points = data[key]
                break
        if raw_points is None:
            for value in data.values():
                if isinstance(value, list):
                    raw_points = value
                    break
    else:
        raw_points = []

    if raw_points is None:
        raw_points = []

    for p in raw_points:
        if isinstance(p, dict):
            if "x" in p and "y" in p:
                points.append((float(p["x"]), float(p["y"])))
            elif "point" in p and len(p["point"]) >= 2:
                points.append((float(p["point"][0]), float(p["point"][1])))
        elif isinstance(p, (list, tuple)) and len(p) >= 2:
            points.append((float(p[0]), float(p[1])))

    return points


def load_fdst_gt_points_map(jsons_dir: Path, frame_ids):
    gt_map = {}

    for frame_id in frame_ids:
        json_path = jsons_dir / f"{frame_id}.json"
        gt_map[frame_id] = load_fdst_points_from_json(json_path)

    return gt_map


mall_gt_points_map = load_mall_gt_points_map(MALL_GT_MAT)
fdst_gt_points_map = load_fdst_gt_points_map(FDST_JSONS_DIR, fdst_df["frame_id"].head(MAX_FDST_FRAMES).tolist())

print("Mall point frames:", len(mall_gt_points_map))
print("FDST point frames:", len(fdst_gt_points_map))

for fid in ["seq_000001", "seq_000002"]:
    print(fid, "Mall points:", len(mall_gt_points_map[fid]), mall_gt_points_map[fid][:3])

for fid in ["100_001", "100_002"]:
    print(fid, "FDST points:", len(fdst_gt_points_map[fid]), fdst_gt_points_map[fid][:3])

Mall point frames: 2000
FDST point frames: 6000
seq_000001 Mall points: 0 []
seq_000002 Mall points: 0 []
100_001 FDST points: 20 [(1339.0, 851.0), (1570.0, 610.0), (823.0, 647.0)]
100_002 FDST points: 20 [(1339.0, 850.0), (1481.0, 610.0), (823.0, 647.0)]

In [23]:
from scipy.io import loadmat
import numpy as np

mat = loadmat(MALL_GT_MAT)

print("Keys:", mat.keys())
print("frame type:", type(mat["frame"]))
print("frame shape:", mat["frame"].shape)
print("count shape:", mat["count"].shape)

entry = mat["frame"][0, 0]

print("\nFirst frame entry type:", type(entry))
print("First frame entry dtype:", getattr(entry, "dtype", None))
print("First frame entry shape:", getattr(entry, "shape", None))
print("First frame entry:", entry)

def recursive_print(obj, depth=0, max_depth=5, name="root"):
    indent = "  " * depth
    print(f"{indent}{name}: type={type(obj)}, shape={getattr(obj, 'shape', None)}, dtype={getattr(obj, 'dtype', None)}")

    if depth >= max_depth:
        return

    if isinstance(obj, np.ndarray):
        if obj.dtype.names:
            print(f"{indent}fields: {obj.dtype.names}")
            for field in obj.dtype.names:
                recursive_print(obj[field], depth + 1, max_depth, field)
        else:
            flat = list(obj.flat)
            for i, item in enumerate(flat[:5]):
                recursive_print(item, depth + 1, max_depth, f"item[{i}]")

recursive_print(entry, max_depth=6)

Keys: dict_keys(['__header__', '__version__', '__globals__', 'frame', 'count'])
frame type: <class 'numpy.ndarray'>
frame shape: (1, 2000)
count shape: (2000, 1)

First frame entry type: <class 'numpy.ndarray'>
First frame entry dtype: [('loc', 'O')]
First frame entry shape: (1, 1)
First frame entry: [[(array([[126.77986348,  60.70477816],
         [116.95051195,  47.59897611],
         [175.10750853,  44.3225256 ],
         [184.11774744,  45.14163823],
         [192.30887372,  44.3225256 ],
         [230.80716724,  42.68430034],
         [190.67064846,  66.43856655],
         [176.74573379,  70.53412969],
         [134.97098976, 100.0221843 ],
         [ 14.56143345, 215.51706485],
         [ 57.1552901 , 229.44197952],
         [148.07679181, 193.40102389],
         [143.16211604, 236.81399317],
         [210.32935154, 222.8890785 ],
         [260.29522184, 221.25085324],
         [348.75938567, 225.34641638],
         [364.3225256 , 253.19624573],
         [331.55802048, 249.10068259],
         [136.60921502, 370.32935154],
         [330.73890785, 453.87883959],
         [387.25767918, 433.40102389],
         [397.08703072, 315.44880546],
         [531.42150171, 324.45904437],
         [563.3668942 , 299.88566553],
         [581.38737201, 300.70477816],
         [566.64334471, 140.15870307],
         [524.04948805, 122.13822526],
         [536.33617747, 117.22354949],
         [560.90955631, 118.86177474]]),)]]
root: type=<class 'numpy.ndarray'>, shape=(1, 1), dtype=[('loc', 'O')]
fields: ('loc',)
  loc: type=<class 'numpy.ndarray'>, shape=(1, 1), dtype=object
    item[0]: type=<class 'numpy.ndarray'>, shape=(29, 2), dtype=float64
      item[0]: type=<class 'numpy.float64'>, shape=(), dtype=float64
      item[1]: type=<class 'numpy.float64'>, shape=(), dtype=float64
      item[2]: type=<class 'numpy.float64'>, shape=(), dtype=float64
      item[3]: type=<class 'numpy.float64'>, shape=(), dtype=float64
      item[4]: type=<class 'numpy.float64'>, shape=(), dtype=float64

In [24]:
def load_mall_gt_points_map(gt_mat_path: Path):
    """
    Correct Mall point loader.
    Mall structure:
        mat["frame"][0, i]["loc"][0, 0] -> Nx2 array
    """
    mat = loadmat(gt_mat_path)
    frame_data = mat["frame"]

    gt_map = {}

    for i in range(frame_data.shape[1]):
        frame_id = f"seq_{i+1:06d}"

        loc = frame_data[0, i]["loc"][0, 0]

        points = [(float(x), float(y)) for x, y in loc]
        gt_map[frame_id] = points

    return gt_map


mall_gt_points_map = load_mall_gt_points_map(MALL_GT_MAT)

print("Mall point frames:", len(mall_gt_points_map))

for fid in ["seq_000001", "seq_000002", "seq_000003"]:
    print(fid, "points:", len(mall_gt_points_map[fid]), "count csv:", mall_df[mall_df["frame_id"] == fid]["gt_count"].iloc[0])
    print("sample:", mall_gt_points_map[fid][:3])

Mall point frames: 2000
seq_000001 points: 29 count csv: 29
sample: [(126.77986348122866, 60.70477815699661), (116.95051194539244, 47.59897610921496), (175.10750853242317, 44.32252559726953)]
seq_000002 points: 30 count csv: 30
sample: [(57.155290102389046, 199.13481228668945), (87.46245733788388, 209.7832764505119), (169.3737201365187, 205.68771331058014)]
seq_000003 points: 35 count csv: 35
sample: [(118.73899371069183, 43.77044025157227), (134.83962264150946, 44.776729559748276), (175.0911949685535, 43.770440251572154)]

In [25]:
from scipy.optimize import linear_sum_assignment
import numpy as np

def compute_localization_metrics(gt_points, pred_points, distance_threshold: float = 16.0):
    """
    Compute point-level localization Precision, Recall, and F1.

    A prediction is a true positive if it is matched to one GT point
    within distance_threshold pixels. Matching is one-to-one using Hungarian assignment.
    """
    gt = np.array(gt_points, dtype=np.float32)

    # pred_points can be [(x,y)] or [(x,y,score)]
    pred = np.array([(p[0], p[1]) for p in pred_points], dtype=np.float32)

    if len(gt) == 0 and len(pred) == 0:
        return {"tp": 0, "fp": 0, "fn": 0, "precision": 1.0, "recall": 1.0, "f1": 1.0}

    if len(gt) == 0:
        return {"tp": 0, "fp": len(pred), "fn": 0, "precision": 0.0, "recall": 1.0, "f1": 0.0}

    if len(pred) == 0:
        return {"tp": 0, "fp": 0, "fn": len(gt), "precision": 1.0, "recall": 0.0, "f1": 0.0}

    dists = np.linalg.norm(gt[:, None, :] - pred[None, :, :], axis=2)

    row_ind, col_ind = linear_sum_assignment(dists)

    matched_distances = dists[row_ind, col_ind]
    valid_matches = matched_distances <= distance_threshold

    tp = int(np.sum(valid_matches))
    fp = int(len(pred) - tp)
    fn = int(len(gt) - tp)

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    return {
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
    }


sample_row = mall_df.iloc[0]
result = predict_fidtm_points(
    sample_row["image_path"],
    threshold=FIDTM_THRESHOLD,
    nms_kernel=FIDTM_NMS_KERNEL,
)

loc = compute_localization_metrics(
    gt_points=mall_gt_points_map[sample_row["frame_id"]],
    pred_points=result["points"],
    distance_threshold=16.0,
)

print("Frame:", sample_row["frame_id"])
print("GT count:", sample_row["gt_count"])
print("Pred count:", result["count"])
print(loc)

Frame: seq_000001
GT count: 29
Pred count: 33
{'tp': 21, 'fp': 12, 'fn': 8, 'precision': 0.6363636363636364, 'recall': 0.7241379310344828, 'f1': 0.6774193548387097}

/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:454: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x1 = F.upsample(x[1], size=(x0_h, x0_w), mode='bilinear')
/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:455: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x2 = F.upsample(x[2], size=(x0_h, x0_w), mode='bilinear')
/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:456: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x3 = F.upsample(x[3], size=(x0_h, x0_w), mode='bilinear')

In [26]:
def get_gt_points(dataset: str, frame_id: str):
    if dataset == "Mall":
        return mall_gt_points_map[frame_id]
    if dataset == "FDST":
        return fdst_gt_points_map[frame_id]
    raise ValueError(f"Unknown dataset: {dataset}")


def run_fidtm_full_metrics(samples_df: pd.DataFrame, distance_threshold: float = 16.0):
    rows = []

    for _, row in tqdm(samples_df.iterrows(), total=len(samples_df)):
        pred = predict_fidtm_points(
            row["image_path"],
            threshold=FIDTM_THRESHOLD,
            nms_kernel=FIDTM_NMS_KERNEL,
        )

        gt_points = get_gt_points(row["dataset"], row["frame_id"])

        loc = compute_localization_metrics(
            gt_points=gt_points,
            pred_points=pred["points"],
            distance_threshold=distance_threshold,
        )

        pred_count = int(pred["count"])
        gt_count = int(row["gt_count"])

        rows.append({
            "model": "FIDTM",
            "dataset": row["dataset"],
            "frame_id": row["frame_id"],
            "gt_count": gt_count,
            "pred_count": pred_count,
            "abs_error": abs(pred_count - gt_count),
            "sq_error": (pred_count - gt_count) ** 2,
            "time_sec": float(pred["time_sec"]),
            "fps": float(1.0 / pred["time_sec"]) if pred["time_sec"] > 0 else 0.0,
            "tp": loc["tp"],
            "fp": loc["fp"],
            "fn": loc["fn"],
            "precision": loc["precision"],
            "recall": loc["recall"],
            "f1": loc["f1"],
        })

    return pd.DataFrame(rows)


fidtm_quick_full_df = run_fidtm_full_metrics(quick_samples, distance_threshold=16.0)

fidtm_quick_full_summary = (
    fidtm_quick_full_df
    .groupby(["model", "dataset"])
    .agg(
        frames=("frame_id", "count"),
        mae=("abs_error", "mean"),
        rmse=("sq_error", lambda x: float(np.sqrt(np.mean(x)))),
        avg_fps=("fps", "mean"),
        avg_time_sec=("time_sec", "mean"),
        total_tp=("tp", "sum"),
        total_fp=("fp", "sum"),
        total_fn=("fn", "sum"),
    )
    .reset_index()
)

fidtm_quick_full_summary["precision"] = (
    fidtm_quick_full_summary["total_tp"] /
    (fidtm_quick_full_summary["total_tp"] + fidtm_quick_full_summary["total_fp"])
)

fidtm_quick_full_summary["recall"] = (
    fidtm_quick_full_summary["total_tp"] /
    (fidtm_quick_full_summary["total_tp"] + fidtm_quick_full_summary["total_fn"])
)

fidtm_quick_full_summary["f1"] = (
    2 * fidtm_quick_full_summary["precision"] * fidtm_quick_full_summary["recall"] /
    (fidtm_quick_full_summary["precision"] + fidtm_quick_full_summary["recall"])
)

display(fidtm_quick_full_summary)

  0%|          | 0/200 [00:00<?, ?it/s]

,model,dataset,frames,mae,rmse,avg_fps,avg_time_sec,total_tp,total_fp,total_fn,precision,recall,f1
0,FIDTM,FDST,100,3.86,4.349713,1.764276,0.567690,2007,560,182,0.781847,0.916857,0.843987
1,FIDTM,Mall,100,2.02,2.687006,9.018078,0.112459,1879,707,729,0.726605,0.720475,0.723527

In [27]:
full_samples = pd.concat([
    mall_df,
    fdst_df.head(MAX_FDST_FRAMES),
], ignore_index=True)

print("Full samples:")
print(full_samples["dataset"].value_counts())
print("Total:", len(full_samples))

fidtm_full_df = run_fidtm_full_metrics(
    full_samples,
    distance_threshold=16.0,
)

fidtm_full_summary = (
    fidtm_full_df
    .groupby(["model", "dataset"])
    .agg(
        frames=("frame_id", "count"),
        mae=("abs_error", "mean"),
        rmse=("sq_error", lambda x: float(np.sqrt(np.mean(x)))),
        avg_fps=("fps", "mean"),
        avg_time_sec=("time_sec", "mean"),
        total_tp=("tp", "sum"),
        total_fp=("fp", "sum"),
        total_fn=("fn", "sum"),
        mean_gt=("gt_count", "mean"),
        mean_pred=("pred_count", "mean"),
    )
    .reset_index()
)

fidtm_full_summary["precision"] = (
    fidtm_full_summary["total_tp"] /
    (fidtm_full_summary["total_tp"] + fidtm_full_summary["total_fp"])
)

fidtm_full_summary["recall"] = (
    fidtm_full_summary["total_tp"] /
    (fidtm_full_summary["total_tp"] + fidtm_full_summary["total_fn"])
)

fidtm_full_summary["f1"] = (
    2 * fidtm_full_summary["precision"] * fidtm_full_summary["recall"] /
    (fidtm_full_summary["precision"] + fidtm_full_summary["recall"])
)

display(fidtm_full_summary)

# Save full results
fidtm_full_predictions_csv = BENCH_DIR / "FIDTM_full_predictions_mall_fdst6000.csv"
fidtm_full_summary_csv = BENCH_DIR / "FIDTM_full_summary_mall_fdst6000.csv"

fidtm_full_df.to_csv(fidtm_full_predictions_csv, index=False)
fidtm_full_summary.to_csv(fidtm_full_summary_csv, index=False)

print("Saved predictions:", fidtm_full_predictions_csv)
print("Saved summary:", fidtm_full_summary_csv)

Full samples:
dataset
FDST    6000
Mall    2000
Name: count, dtype: int64
Total: 8000

  0%|          | 0/8000 [00:00<?, ?it/s]

/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:454: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x1 = F.upsample(x[1], size=(x0_h, x0_w), mode='bilinear')
/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:455: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x2 = F.upsample(x[2], size=(x0_h, x0_w), mode='bilinear')
/kaggle/working/repos/FIDTM/Networks/HR_Net/seg_hrnet.py:456: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.
  x3 = F.upsample(x[3], size=(x0_h, x0_w), mode='bilinear')

,model,dataset,frames,mae,rmse,avg_fps,avg_time_sec,total_tp,total_fp,total_fn,mean_gt,mean_pred,precision,recall,f1
0,FIDTM,FDST,6000,3.6135,4.736578,2.269182,0.489558,89871,27295,37646,21.252833,19.527667,0.767040,0.704777,0.734591
1,FIDTM,Mall,2000,3.1670,3.937893,8.957016,0.113403,41897,15786,20418,31.157500,28.841500,0.726332,0.672342,0.698295

Saved predictions: /kaggle/working/benchmark_results/FIDTM_full_predictions_mall_fdst6000.csv
Saved summary: /kaggle/working/benchmark_results/FIDTM_full_summary_mall_fdst6000.csv

In [28]:
import os
import sys
from pathlib import Path

PET_REPO = REPOS_DIR / "PET"

os.chdir(PET_REPO)

if str(PET_REPO) not in sys.path:
    sys.path.insert(0, str(PET_REPO))

print("PET repo:", PET_REPO)

for f in [
    "main.py",
    "models/pet.py",
    "test_single_image.py",
    "eval.py"
]:
    p = PET_REPO / f
    print("\n", "="*70)
    print(f)

    with open(p, "r", encoding="utf8", errors="ignore") as fp:
        lines = fp.readlines()

    for i, line in enumerate(lines[:120]):
        print(f"{i+1:03d}: {line.rstrip()}")

PET repo: /kaggle/working/repos/PET

 ======================================================================
main.py
001: import argparse
002: import datetime
003: import json
004: import random
005: import time
006: from pathlib import Path
007: import os
008: import shutil
009:
010: import numpy as np
011: import torch
012: import torch.nn as nn
013: from torch.utils.data import DataLoader, DistributedSampler
014:
015: import datasets
016: import util.misc as utils
017: from datasets import build_dataset
018: from engine import evaluate, train_one_epoch
019: from models import build_model
020:
021:
022: def get_args_parser():
023:     parser = argparse.ArgumentParser('Set Point Query Transformer', add_help=False)
024:
025:     # training Parameters
026:     parser.add_argument('--lr', default=1e-4, type=float)
027:     parser.add_argument('--lr_backbone', default=1e-5, type=float)
028:     parser.add_argument('--batch_size', default=8, type=int)
029:     parser.add_argument('--weight_decay', default=1e-4, type=float)
030:     parser.add_argument('--epochs', default=1500, type=int)
031:     parser.add_argument('--clip_max_norm', default=0.1, type=float,
032:                         help='gradient clipping max norm')
033:
034:     # model parameters
035:     # - backbone
036:     parser.add_argument('--backbone', default='vgg16_bn', type=str,
037:                         help="Name of the convolutional backbone to use")
038:     parser.add_argument('--position_embedding', default='sine', type=str, choices=('sine', 'learned', 'fourier'),
039:                         help="Type of positional embedding to use on top of the image features")
040:     # - transformer
041:     parser.add_argument('--dec_layers', default=2, type=int,
042:                         help="Number of decoding layers in the transformer")
043:     parser.add_argument('--dim_feedforward', default=512, type=int,
044:                         help="Intermediate size of the feedforward layers in the transformer blocks")
045:     parser.add_argument('--hidden_dim', default=256, type=int,
046:                         help="Size of the embeddings (dimension of the transformer)")
047:     parser.add_argument('--dropout', default=0.0, type=float,
048:                         help="Dropout applied in the transformer")
049:     parser.add_argument('--nheads', default=8, type=int,
050:                         help="Number of attention heads inside the transformer's attentions")
051:
052:     # loss parameters
053:     # - matcher
054:     parser.add_argument('--set_cost_class', default=1, type=float,
055:                         help="Class coefficient in the matching cost")
056:     parser.add_argument('--set_cost_point', default=0.05, type=float,
057:                         help="SmoothL1 point coefficient in the matching cost")
058:     # - loss coefficients
059:     parser.add_argument('--ce_loss_coef', default=1.0, type=float)
060:     parser.add_argument('--point_loss_coef', default=5.0, type=float)
061:     parser.add_argument('--eos_coef', default=0.5, type=float,
062:                         help="Relative classification weight of the no-object class")
063:
064:     # dataset parameters
065:     parser.add_argument('--dataset_file', default="SHA")
066:     parser.add_argument('--data_path', default="./data/ShanghaiTech/PartA", type=str)
067:
068:     # misc parameters
069:     parser.add_argument('--output_dir', default='',
070:                         help='path where to save, empty for no saving')
071:     parser.add_argument('--device', default='cuda',
072:                         help='device to use for training / testing')
073:     parser.add_argument('--seed', default=42, type=int)
074:     parser.add_argument('--resume', default='', help='resume from checkpoint')
075:     parser.add_argument('--start_epoch', default=0, type=int, metavar='N',
076:                         help='start epoch')
077:     parser.add_argument('--num_workers', default=2, type=int)
078:     parser.add_argument('--eval_freq', default=5, type=int)
079:     parser.add_argument('--syn_bn', default=0, type=int)
080:
081:     # distributed training parameters
082:     parser.add_argument('--world_size', default=1, type=int,
083:                         help='number of distributed processes')
084:     parser.add_argument('--dist_url', default='env://', help='url used to set up distributed training')
085:     return parser
086:
087:
088: def main(args):
089:     utils.init_distributed_mode(args)
090:     print(args)
091:     device = torch.device(args.device)
092:
093:     # fix the seed for reproducibility
094:     seed = args.seed + utils.get_rank()
095:     torch.manual_seed(seed)
096:     np.random.seed(seed)
097:     random.seed(seed)
098:
099:     # build model
100:     model, criterion = build_model(args)
101:     model.to(device)
102:     if args.syn_bn:
103:         model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
104:
105:     model_without_ddp = model
106:     if args.distributed:
107:         model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu], find_unused_parameters=True)
108:         model_without_ddp = model.module
109:     n_parameters = sum(p.numel() for p in model.parameters() if p.requires_grad)
110:
111:     # build optimizer
112:     param_dicts = [
113:         {"params": [p for n, p in model_without_ddp.named_parameters() if "backbone" not in n and p.requires_grad]},
114:         {
115:             "params": [p for n, p in model_without_ddp.named_parameters() if "backbone" in n and p.requires_grad],
116:             "lr": args.lr_backbone,
117:         },
118:     ]
119:     optimizer = torch.optim.AdamW(param_dicts, lr=args.lr,
120:                                   weight_decay=args.weight_decay)

 ======================================================================
models/pet.py
001: """
002: PET model and criterion classes
003: """
004: import torch
005: import torch.nn.functional as F
006: from torch import nn
007:
008: from util.misc import (NestedTensor, nested_tensor_from_tensor_list,
009:                        get_world_size, is_dist_avail_and_initialized)
010:
011: from .matcher import build_matcher
012: from .backbones import *
013: from .transformer import *
014: from .position_encoding import build_position_encoding
015:
016:
017: class BasePETCount(nn.Module):
018:     """
019:     Base PET model
020:     """
021:     def __init__(self, backbone, num_classes, quadtree_layer='sparse', args=None, **kwargs):
022:         super().__init__()
023:         self.backbone = backbone
024:         self.transformer = kwargs['transformer']
025:         hidden_dim = args.hidden_dim
026:
027:         self.class_embed = nn.Linear(hidden_dim, num_classes + 1)
028:         self.coord_embed = MLP(hidden_dim, hidden_dim, 2, 3)
029:
030:         self.pq_stride = args.sparse_stride if quadtree_layer == 'sparse' else args.dense_stride
031:         self.feat_name = '8x' if quadtree_layer == 'sparse' else '4x'
032:
033:     def points_queris_embed(self, samples, stride=8, src=None, **kwargs):
034:         """
035:         Generate point query embedding during training
036:         """
037:         # dense position encoding at every pixel location
038:         dense_input_embed = kwargs['dense_input_embed']
039:         bs, c = dense_input_embed.shape[:2]
040:
041:         # get image shape
042:         input = samples.tensors
043:         image_shape = torch.tensor(input.shape[2:])
044:         shape = (image_shape + stride//2 -1) // stride
045:
046:         # generate point queries
047:         shift_x = ((torch.arange(0, shape[1]) + 0.5) * stride).long()
048:         shift_y = ((torch.arange(0, shape[0]) + 0.5) * stride).long()
049:         shift_y, shift_x = torch.meshgrid(shift_y, shift_x)
050:         points_queries = torch.vstack([shift_y.flatten(), shift_x.flatten()]).permute(1,0) # 2xN --> Nx2
051:         h, w = shift_x.shape
052:
053:         # get point queries embedding
054:         query_embed = dense_input_embed[:, :, points_queries[:, 0], points_queries[:, 1]]
055:         bs, c = query_embed.shape[:2]
056:         query_embed = query_embed.view(bs, c, h, w)
057:
058:         # get point queries features, equivalent to nearest interpolation
059:         shift_y_down, shift_x_down = points_queries[:, 0] // stride, points_queries[:, 1] // stride
060:         query_feats = src[:, :, shift_y_down,shift_x_down]
061:         query_feats = query_feats.view(bs, c, h, w)
062:
063:         return query_embed, points_queries, query_feats
064:
065:     def points_queris_embed_inference(self, samples, stride=8, src=None, **kwargs):
066:         """
067:         Generate point query embedding during inference
068:         """
069:         # dense position encoding at every pixel location
070:         dense_input_embed = kwargs['dense_input_embed']
071:         bs, c = dense_input_embed.shape[:2]
072:
073:         # get image shape
074:         input = samples.tensors
075:         image_shape = torch.tensor(input.shape[2:])
076:         shape = (image_shape + stride//2 -1) // stride
077:
078:         # generate points queries
079:         shift_x = ((torch.arange(0, shape[1]) + 0.5) * stride).long()
080:         shift_y = ((torch.arange(0, shape[0]) + 0.5) * stride).long()
081:         shift_y, shift_x = torch.meshgrid(shift_y, shift_x)
082:         points_queries = torch.vstack([shift_y.flatten(), shift_x.flatten()]).permute(1,0) # 2xN --> Nx2
083:         h, w = shift_x.shape
084:
085:         # get points queries embedding
086:         query_embed = dense_input_embed[:, :, points_queries[:, 0], points_queries[:, 1]]
087:         bs, c = query_embed.shape[:2]
088:
089:         # get points queries features, equivalent to nearest interpolation
090:         shift_y_down, shift_x_down = points_queries[:, 0] // stride, points_queries[:, 1] // stride
091:         query_feats = src[:, :, shift_y_down, shift_x_down]
092:
093:         # window-rize
094:         query_embed = query_embed.reshape(bs, c, h, w)
095:         points_queries = points_queries.reshape(h, w, 2).permute(2, 0, 1).unsqueeze(0)
096:         query_feats = query_feats.reshape(bs, c, h, w)
097:
098:         dec_win_w, dec_win_h = kwargs['dec_win_size']
099:         query_embed_win = window_partition(query_embed, window_size_h=dec_win_h, window_size_w=dec_win_w)
100:         points_queries_win = window_partition(points_queries, window_size_h=dec_win_h, window_size_w=dec_win_w)
101:         query_feats_win = window_partition(query_feats, window_size_h=dec_win_h, window_size_w=dec_win_w)
102:
103:         # dynamic point query generation
104:         div = kwargs['div']
105:         div_win = window_partition(div.unsqueeze(1), window_size_h=dec_win_h, window_size_w=dec_win_w)
106:         valid_div = (div_win > 0.5).sum(dim=0)[:,0]
107:         v_idx = valid_div > 0
108:         query_embed_win = query_embed_win[:, v_idx]
109:         query_feats_win = query_feats_win[:, v_idx]
110:         points_queries_win = points_queries_win[:, v_idx].reshape(-1, 2)
111:
112:         return query_embed_win, points_queries_win, query_feats_win, v_idx
113:
114:     def get_point_query(self, samples, features, **kwargs):
115:         """
116:         Generate point query
117:         """
118:         src, _ = features[self.feat_name].decompose()
119:
120:         # generate points queries and position embedding

 ======================================================================
test_single_image.py
001: import argparse
002: import os
003: import cv2
004: import numpy as np
005: from PIL import Image
006: import torch
007: import torchvision.transforms as standard_transforms
008:
009: import util.misc as utils
010: from models import build_model
011:
012:
013: def get_args_parser():
014:     parser = argparse.ArgumentParser('Set Point Query Transformer', add_help=False)
015:
016:     # model parameters
017:     # - backbone
018:     parser.add_argument('--backbone', default='vgg16_bn', type=str,
019:                         help="Name of the convolutional backbone to use")
020:     parser.add_argument('--position_embedding', default='sine', type=str, choices=('sine', 'learned', 'fourier'),
021:                         help="Type of positional embedding to use on top of the image features")
022:     # - transformer
023:     parser.add_argument('--dec_layers', default=2, type=int,
024:                         help="Number of decoding layers in the transformer")
025:     parser.add_argument('--dim_feedforward', default=512, type=int,
026:                         help="Intermediate size of the feedforward layers in the transformer blocks")
027:     parser.add_argument('--hidden_dim', default=256, type=int,
028:                         help="Size of the embeddings (dimension of the transformer)")
029:     parser.add_argument('--dropout', default=0.0, type=float,
030:                         help="Dropout applied in the transformer")
031:     parser.add_argument('--nheads', default=8, type=int,
032:                         help="Number of attention heads inside the transformer's attentions")
033:
034:     # loss parameters
035:     # - matcher
036:     parser.add_argument('--set_cost_class', default=1, type=float,
037:                         help="Class coefficient in the matching cost")
038:     parser.add_argument('--set_cost_point', default=0.05, type=float,
039:                         help="SmoothL1 point coefficient in the matching cost")
040:     # - loss coefficients
041:     parser.add_argument('--ce_loss_coef', default=1.0, type=float)       # classification loss coefficient
042:     parser.add_argument('--point_loss_coef', default=5.0, type=float)    # regression loss coefficient
043:     parser.add_argument('--eos_coef', default=0.5, type=float,
044:                         help="Relative classification weight of the no-object class")   # cross-entropy weights
045:
046:     # dataset parameters
047:     parser.add_argument('--dataset_file', default="SHA")
048:     parser.add_argument('--data_path', default="./data/ShanghaiTech/PartA", type=str)
049:
050:     # misc parameters
051:     parser.add_argument('--device', default='cuda',
052:                         help='device to use for training / testing')
053:     parser.add_argument('--seed', default=42, type=int)
054:     parser.add_argument('--resume', default='', help='resume from checkpoint')
055:     parser.add_argument('--vis_dir', default="")
056:     parser.add_argument('--num_workers', default=2, type=int)
057:
058:     # distributed training parameters
059:     parser.add_argument('--world_size', default=1, type=int,
060:                         help='number of distributed processes')
061:     parser.add_argument('--dist_url', default='env://', help='url used to set up distributed training')
062:     return parser
063:
064:
065: class DeNormalize(object):
066:     def __init__(self, mean, std):
067:         self.mean = mean
068:         self.std = std
069:
070:     def __call__(self, tensor):
071:         for t, m, s in zip(tensor, self.mean, self.std):
072:             t.mul_(s).add_(m)
073:         return tensor
074:
075:
076: def visualization(samples, pred, vis_dir, img_path, split_map=None):
077:     """
078:     Visualize predictions
079:     """
080:     pil_to_tensor = standard_transforms.ToTensor()
081:
082:     restore_transform = standard_transforms.Compose([
083:         DeNormalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
084:         standard_transforms.ToPILImage()
085:     ])
086:
087:     images = samples.tensors
088:     masks = samples.mask
089:     for idx in range(images.shape[0]):
090:         sample = restore_transform(images[idx])
091:         sample = pil_to_tensor(sample.convert('RGB')).numpy() * 255
092:         sample_vis = sample.transpose([1, 2, 0])[:, :, ::-1].astype(np.uint8).copy()
093:
094:         # draw predictions (green)
095:         size = 3
096:         for p in pred[idx]:
097:             sample_vis = cv2.circle(sample_vis, (int(p[1]), int(p[0])), size, (0, 255, 0), -1)
098:
099:         # draw split map
100:         if split_map is not None:
101:             imgH, imgW = sample_vis.shape[:2]
102:             split_map = (split_map * 255).astype(np.uint8)
103:             split_map = cv2.applyColorMap(split_map, cv2.COLORMAP_JET)
104:             split_map = cv2.resize(split_map, (imgW, imgH), interpolation=cv2.INTER_NEAREST)
105:             sample_vis = split_map * 0.9 + sample_vis
106:
107:         # save image
108:         if vis_dir is not None:
109:             # eliminate invalid area
110:             imgH, imgW = masks.shape[-2:]
111:             valid_area = torch.where(~masks[idx])
112:             valid_h, valid_w = valid_area[0][-1], valid_area[1][-1]
113:             sample_vis = sample_vis[:valid_h+1, :valid_w+1]
114:
115:             name = img_path.split('/')[-1].split('.')[0]
116:             img_save_path = os.path.join(vis_dir, '{}_pred{}.jpg'.format(name, len(pred[idx])))
117:             cv2.imwrite(img_save_path, sample_vis)
118:             print('image save to ', img_save_path)
119:
120:

 ======================================================================
eval.py
001: import argparse
002: import random
003: from pathlib import Path
004: import os
005:
006: import numpy as np
007: import torch
008: import torch.nn as nn
009: from torch.utils.data import DataLoader, DistributedSampler
010:
011: import datasets
012: from datasets import build_dataset
013: import util.misc as utils
014: from engine import evaluate
015: from models import build_model
016:
017:
018: def get_args_parser():
019:     parser = argparse.ArgumentParser('Set Point Query Transformer', add_help=False)
020:
021:     # model parameters
022:     # - backbone
023:     parser.add_argument('--backbone', default='vgg16_bn', type=str,
024:                         help="Name of the convolutional backbone to use")
025:     parser.add_argument('--position_embedding', default='sine', type=str, choices=('sine', 'learned', 'fourier'),
026:                         help="Type of positional embedding to use on top of the image features")
027:     # - transformer
028:     parser.add_argument('--dec_layers', default=2, type=int,
029:                         help="Number of decoding layers in the transformer")
030:     parser.add_argument('--dim_feedforward', default=512, type=int,
031:                         help="Intermediate size of the feedforward layers in the transformer blocks")
032:     parser.add_argument('--hidden_dim', default=256, type=int,
033:                         help="Size of the embeddings (dimension of the transformer)")
034:     parser.add_argument('--dropout', default=0.0, type=float,
035:                         help="Dropout applied in the transformer")
036:     parser.add_argument('--nheads', default=8, type=int,
037:                         help="Number of attention heads inside the transformer's attentions")
038:
039:     # loss parameters
040:     # - matcher
041:     parser.add_argument('--set_cost_class', default=1, type=float,
042:                         help="Class coefficient in the matching cost")
043:     parser.add_argument('--set_cost_point', default=0.05, type=float,
044:                         help="SmoothL1 point coefficient in the matching cost")
045:     # - loss coefficients
046:     parser.add_argument('--ce_loss_coef', default=1.0, type=float)       # classification loss coefficient
047:     parser.add_argument('--point_loss_coef', default=5.0, type=float)    # regression loss coefficient
048:     parser.add_argument('--eos_coef', default=0.5, type=float,
049:                         help="Relative classification weight of the no-object class")   # cross-entropy weights
050:
051:     # dataset parameters
052:     parser.add_argument('--dataset_file', default="SHA")

In [30]:
import urllib.request
from pathlib import Path

PET_PRETRAINED_DIR = PET_REPO / "pretrained"
PET_PRETRAINED_DIR.mkdir(parents=True, exist_ok=True)

VGG_PATH = PET_PRETRAINED_DIR / "vgg16_bn-6c64b313.pth"
VGG_URL = "https://download.pytorch.org/models/vgg16_bn-6c64b313.pth"

if not VGG_PATH.exists():
    print("Downloading VGG16-BN backbone...")
    urllib.request.urlretrieve(VGG_URL, VGG_PATH)
else:
    print("VGG16-BN already exists.")

print("VGG path:", VGG_PATH)
print("Exists:", VGG_PATH.exists())
print("Size MB:", VGG_PATH.stat().st_size / (1024 * 1024))

Downloading VGG16-BN backbone...
VGG path: /kaggle/working/repos/PET/pretrained/vgg16_bn-6c64b313.pth
Exists: True
Size MB: 527.8662071228027

In [31]:
import os
import sys
import torch
from argparse import Namespace

PET_REPO = REPOS_DIR / "PET"
os.chdir(PET_REPO)

if str(PET_REPO) not in sys.path:
    sys.path.insert(0, str(PET_REPO))

from models import build_model

pet_args = Namespace(
    backbone='vgg16_bn',
    position_embedding='sine',
    dec_layers=2,
    dim_feedforward=512,
    hidden_dim=256,
    dropout=0.0,
    nheads=8,

    set_cost_class=1,
    set_cost_point=0.05,

    ce_loss_coef=1.0,
    point_loss_coef=5.0,
    eos_coef=0.5,

    dataset_file='SHA',
    data_path='',

    device='cuda',
    seed=42,
    resume='',
    vis_dir='',
    num_workers=2,

    world_size=1,
    dist_url='env://',

    distributed=False,
    gpu=0,
)

pet_model, pet_criterion = build_model(pet_args)

ckpt = torch.load(PET_WEIGHT_PATH, map_location='cpu')
pet_model.load_state_dict(ckpt["model"])

pet_model = pet_model.to(DEVICE)
pet_model.eval()

print("PET loaded successfully")

PET loaded successfully

In [33]:
# Inspect PET build_pet args and window defaults
pet_py = PET_REPO / "models" / "pet.py"

with open(pet_py, "r", encoding="utf8", errors="ignore") as f:
    lines = f.readlines()

for start, end in [(560, 640), (300, 380), (120, 220)]:
    print("\n" + "="*80)
    print(f"models/pet.py lines {start}-{end}")
    print("="*80)
    for i in range(start-1, min(end, len(lines))):
        print(f"{i+1:03d}: {lines[i].rstrip()}")

================================================================================
models/pet.py lines 560-640
================================================================================
560:     Multi-layer perceptron (also called FFN)
561:     """
562:     def __init__(self, input_dim, hidden_dim, output_dim, num_layers, is_reduce=False, use_relu=True):
563:         super().__init__()
564:         self.num_layers = num_layers
565:         if is_reduce:
566:             h = [hidden_dim//2**i for i in range(num_layers - 1)]
567:         else:
568:             h = [hidden_dim] * (num_layers - 1)
569:         self.layers = nn.ModuleList(nn.Linear(n, k) for n, k in zip([input_dim] + h, h + [output_dim]))
570:         self.use_relu = use_relu
571:
572:     def forward(self, x):
573:         for i, layer in enumerate(self.layers):
574:             if self.use_relu:
575:                 x = F.relu(layer(x)) if i < self.num_layers - 1 else layer(x)
576:             else:
577:                 x = layer(x)
578:         return x
579:
580:
581: def build_pet(args):
582:     device = torch.device(args.device)
583:
584:     # build model
585:     num_classes = 1
586:     backbone = build_backbone_vgg(args)
587:     model = PET(
588:         backbone,
589:         num_classes=num_classes,
590:         args=args,
591:     )
592:
593:     # build loss criterion
594:     matcher = build_matcher(args)
595:     weight_dict = {'loss_ce': args.ce_loss_coef, 'loss_points': args.point_loss_coef}
596:     losses = ['labels', 'points']
597:     criterion = SetCriterion(num_classes, matcher=matcher, weight_dict=weight_dict,
598:                              eos_coef=args.eos_coef, losses=losses)
599:     criterion.to(device)
600:     return model, criterion

================================================================================
models/pet.py lines 300-380
================================================================================
300:         # forward
301:         if 'train' in kwargs:
302:             out = self.train_forward(samples, features, pos, **kwargs)
303:         else:
304:             out = self.test_forward(samples, features, pos, **kwargs)
305:         return out
306:
307:     def pet_forward(self, samples, features, pos, **kwargs):
308:         # context encoding
309:         src, mask = features[self.encode_feats].decompose()
310:         src_pos_embed = pos[self.encode_feats]
311:         assert mask is not None
312:         encode_src = self.context_encoder(src, src_pos_embed, mask)
313:         context_info = (encode_src, src_pos_embed, mask)
314:
315:         # apply quadtree splitter
316:         bs, _, src_h, src_w = src.shape
317:         sp_h, sp_w = src_h, src_w
318:         ds_h, ds_w = int(src_h * 2), int(src_w * 2)
319:         split_map = self.quadtree_splitter(encode_src)
320:         split_map_dense = F.interpolate(split_map, (ds_h, ds_w)).reshape(bs, -1)
321:         split_map_sparse = 1 - F.interpolate(split_map, (sp_h, sp_w)).reshape(bs, -1)
322:
323:         # quadtree layer0 forward (sparse)
324:         if 'train' in kwargs or (split_map_sparse > 0.5).sum() > 0:
325:             kwargs['div'] = split_map_sparse.reshape(bs, sp_h, sp_w)
326:             kwargs['dec_win_size'] = [16, 8]
327:             outputs_sparse = self.quadtree_sparse(samples, features, context_info, **kwargs)
328:         else:
329:             outputs_sparse = None
330:
331:         # quadtree layer1 forward (dense)
332:         if 'train' in kwargs or (split_map_dense > 0.5).sum() > 0:
333:             kwargs['div'] = split_map_dense.reshape(bs, ds_h, ds_w)
334:             kwargs['dec_win_size'] = [8, 4]
335:             outputs_dense = self.quadtree_dense(samples, features, context_info, **kwargs)
336:         else:
337:             outputs_dense = None
338:
339:         # format outputs
340:         outputs = dict()
341:         outputs['sparse'] = outputs_sparse
342:         outputs['dense'] = outputs_dense
343:         outputs['split_map_raw'] = split_map
344:         outputs['split_map_sparse'] = split_map_sparse
345:         outputs['split_map_dense'] = split_map_dense
346:         return outputs
347:
348:     def train_forward(self, samples, features, pos, **kwargs):
349:         outputs = self.pet_forward(samples, features, pos, **kwargs)
350:
351:         # compute loss
352:         criterion, targets, epoch = kwargs['criterion'], kwargs['targets'], kwargs['epoch']
353:         losses = self.compute_loss(outputs, criterion, targets, epoch, samples)
354:         return losses
355:
356:     def test_forward(self, samples, features, pos, **kwargs):
357:         outputs = self.pet_forward(samples, features, pos, **kwargs)
358:         out_dense, out_sparse = outputs['dense'], outputs['sparse']
359:         thrs = 0.5  # inference threshold
360:
361:         # process sparse point queries
362:         if outputs['sparse'] is not None:
363:             out_sparse_scores = torch.nn.functional.softmax(out_sparse['pred_logits'], -1)[..., 1]
364:             valid_sparse = out_sparse_scores > thrs
365:             index_sparse = valid_sparse.cpu()
366:         else:
367:             index_sparse = None
368:
369:         # process dense point queries
370:         if outputs['dense'] is not None:
371:             out_dense_scores = torch.nn.functional.softmax(out_dense['pred_logits'], -1)[..., 1]
372:             valid_dense = out_dense_scores > thrs
373:             index_dense = valid_dense.cpu()
374:         else:
375:             index_dense = None
376:
377:         # format output
378:         div_out = dict()
379:         output_names = out_sparse.keys() if out_sparse is not None else out_dense.keys()
380:         for name in list(output_names):

================================================================================
models/pet.py lines 120-220
================================================================================
120:         # generate points queries and position embedding
121:         if 'train' in kwargs:
122:             query_embed, points_queries, query_feats = self.points_queris_embed(samples, self.pq_stride, src, **kwargs)
123:             query_embed = query_embed.flatten(2).permute(2,0,1) # NxCxHxW --> (HW)xNxC
124:             v_idx = None
125:         else:
126:             query_embed, points_queries, query_feats, v_idx = self.points_queris_embed_inference(samples, self.pq_stride, src, **kwargs)
127:
128:         out = (query_embed, points_queries, query_feats, v_idx)
129:         return out
130:
131:     def predict(self, samples, points_queries, hs, **kwargs):
132:         """
133:         Crowd prediction
134:         """
135:         outputs_class = self.class_embed(hs)
136:         # normalize to 0~1
137:         outputs_offsets = (self.coord_embed(hs).sigmoid() - 0.5) * 2.0
138:
139:         # normalize point-query coordinates
140:         img_shape = samples.tensors.shape[-2:]
141:         img_h, img_w = img_shape
142:         points_queries = points_queries.float().cuda()
143:         points_queries[:, 0] /= img_h
144:         points_queries[:, 1] /= img_w
145:
146:         # rescale offset range during testing
147:         if 'test' in kwargs:
148:             outputs_offsets[...,0] /= (img_h / 256)
149:             outputs_offsets[...,1] /= (img_w / 256)
150:
151:         outputs_points = outputs_offsets[-1] + points_queries
152:         out = {'pred_logits': outputs_class[-1], 'pred_points': outputs_points, 'img_shape': img_shape, 'pred_offsets': outputs_offsets[-1]}
153:
154:         out['points_queries'] = points_queries
155:         out['pq_stride'] = self.pq_stride
156:         return out
157:
158:     def forward(self, samples, features, context_info, **kwargs):
159:         encode_src, src_pos_embed, mask = context_info
160:
161:         # get points queries for transformer
162:         pqs = self.get_point_query(samples, features, **kwargs)
163:
164:         # point querying
165:         kwargs['pq_stride'] = self.pq_stride
166:         hs = self.transformer(encode_src, src_pos_embed, mask, pqs, img_shape=samples.tensors.shape[-2:], **kwargs)
167:
168:         # prediction
169:         points_queries = pqs[1]
170:         outputs = self.predict(samples, points_queries, hs, **kwargs)
171:         return outputs
172:
173:
174: class PET(nn.Module):
175:     """
176:     Point quEry Transformer
177:     """
178:     def __init__(self, backbone, num_classes, args=None):
179:         super().__init__()
180:         self.backbone = backbone
181:
182:         # positional embedding
183:         self.pos_embed = build_position_encoding(args)
184:
185:         # feature projection
186:         hidden_dim = args.hidden_dim
187:         self.input_proj = nn.ModuleList([
188:             nn.Conv2d(backbone.num_channels, hidden_dim, kernel_size=1),
189:             nn.Conv2d(backbone.num_channels, hidden_dim, kernel_size=1),
190:             ]
191:         )
192:
193:         # context encoder
194:         self.encode_feats = '8x'
195:         enc_win_list = [(32, 16), (32, 16), (16, 8), (16, 8)]  # encoder window size
196:         args.enc_layers = len(enc_win_list)
197:         self.context_encoder = build_encoder(args, enc_win_list=enc_win_list)
198:
199:         # quadtree splitter
200:         context_patch = (128, 64)
201:         context_w, context_h = context_patch[0]//int(self.encode_feats[:-1]), context_patch[1]//int(self.encode_feats[:-1])
202:         self.quadtree_splitter = nn.Sequential(
203:             nn.AvgPool2d((context_h, context_w), stride=(context_h ,context_w)),
204:             nn.Conv2d(hidden_dim, 1, 1),
205:             nn.Sigmoid(),
206:         )
207:
208:         # point-query quadtree
209:         args.sparse_stride, args.dense_stride = 8, 4    # point-query stride
210:         transformer = build_decoder(args)
211:         self.quadtree_sparse = BasePETCount(backbone, num_classes, quadtree_layer='sparse', args=args, transformer=transformer)
212:         self.quadtree_dense = BasePETCount(backbone, num_classes, quadtree_layer='dense', args=args, transformer=transformer)
213:
214:     def compute_loss(self, outputs, criterion, targets, epoch, samples):
215:         """
216:         Compute loss, including:
217:             - point query loss (Eq. (3) in the paper)
218:             - quadtree splitter loss (Eq. (4) in the paper)
219:         """
220:         output_sparse, output_dense = outputs['sparse'], outputs['dense']

In [41]:
from models.pet import BasePETCount
from models.transformer.utils import window_partition
import torch

def fixed_points_queries_embed_inference(self, samples, stride=8, src=None, **kwargs):
    dense_input_embed = kwargs["dense_input_embed"]
    bs, c = dense_input_embed.shape[:2]

    input_tensor = samples.tensors
    image_shape = torch.tensor(input_tensor.shape[2:])
    shape = (image_shape + stride // 2 - 1) // stride

    shift_x = ((torch.arange(0, shape[1]) + 0.5) * stride).long()
    shift_y = ((torch.arange(0, shape[0]) + 0.5) * stride).long()
    shift_y, shift_x = torch.meshgrid(shift_y, shift_x)

    points_queries = torch.vstack([shift_y.flatten(), shift_x.flatten()]).permute(1, 0)

    h, w = shift_x.shape

    query_embed = dense_input_embed[:, :, points_queries[:, 0], points_queries[:, 1]]
    bs, c = query_embed.shape[:2]

    shift_y_down = points_queries[:, 0] // stride
    shift_x_down = points_queries[:, 1] // stride

    query_feats = src[:, :, shift_y_down, shift_x_down]

    query_embed = query_embed.reshape(bs, c, h, w)
    points_queries = points_queries.reshape(h, w, 2).permute(2, 0, 1).unsqueeze(0)
    query_feats = query_feats.reshape(bs, c, h, w)

    dec_win_w, dec_win_h = kwargs["dec_win_size"]

    query_embed_win = window_partition(
        query_embed,
        window_size_h=dec_win_h,
        window_size_w=dec_win_w,
    )

    points_queries_win = window_partition(
        points_queries,
        window_size_h=dec_win_h,
        window_size_w=dec_win_w,
    )

    query_feats_win = window_partition(
        query_feats,
        window_size_h=dec_win_h,
        window_size_w=dec_win_w,
    )

    div = kwargs["div"]
    div_win = window_partition(
        div.unsqueeze(1),
        window_size_h=dec_win_h,
        window_size_w=dec_win_w,
    )

    valid_div = (div_win > 0.5).sum(dim=0)[:, 0]
    v_idx_gpu = valid_div > 0
    v_idx_cpu = v_idx_gpu.cpu()

    query_embed_win = query_embed_win[:, v_idx_gpu]
    query_feats_win = query_feats_win[:, v_idx_gpu]
    points_queries_win = points_queries_win[:, v_idx_cpu].reshape(-1, 2)

    return query_embed_win, points_queries_win, query_feats_win, v_idx_gpu


BasePETCount.points_queris_embed_inference = fixed_points_queries_embed_inference

print("Correct PET patch installed")

Correct PET patch installed

In [42]:
pet_out, pet_time, pet_original_shape = inspect_pet_output_fixed(
    mall_df.iloc[0]["image_path"]
)

Original shape: (480, 640, 3)
Padded shape: (512, 768, 3)
Output type: <class 'dict'>
Time: 0.1751280210000914
Keys: dict_keys(['pred_logits', 'pred_points', 'img_shape', 'pred_offsets', 'points_queries', 'pq_stride', 'split_map_raw'])
pred_logits torch.Size([1, 25, 2]) -3.9175736904144287 3.1674532890319824
pred_points torch.Size([1, 25, 2]) 0.019360782578587532 0.8829358816146851
img_shape <class 'torch.Size'> torch.Size([512, 768])
pred_offsets torch.Size([1, 25, 2]) -0.00897720456123352 0.00858461856842041
points_queries torch.Size([4992, 2]) 0.0052083334885537624 0.9947916865348816
pq_stride <class 'int'> 8
split_map_raw torch.Size([1, 1, 8, 6]) 6.164415766035658e-13 0.999954104423523

In [43]:
@torch.no_grad()
def predict_pet_points(image_path: str, score_threshold: float = 0.5):
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(image_path)

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    padded, original_shape = pad_to_pet_size(img)

    original_h, original_w = original_shape
    padded_h, padded_w = padded.shape[:2]

    pil = Image.fromarray(padded)
    tensor = pet_transform(pil).to(DEVICE)
    samples = pet_utils.nested_tensor_from_tensor_list([tensor])

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    start = time.perf_counter()
    output = pet_model(samples, test=True)

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    elapsed = time.perf_counter() - start

    logits = output["pred_logits"][0]
    points = output["pred_points"][0]

    scores = torch.softmax(logits, dim=-1)[:, 1]

    valid = scores >= score_threshold

    points = points[valid].detach().cpu().numpy()
    scores = scores[valid].detach().cpu().numpy()

    pred_points = []

    for p, s in zip(points, scores):
        # PET point format is normalized (y, x)
        y = float(p[0] * padded_h)
        x = float(p[1] * padded_w)

        # Remove points outside original unpadded image
        if 0 <= x < original_w and 0 <= y < original_h:
            pred_points.append((x, y, float(s)))

    return {
        "count": len(pred_points),
        "points": pred_points,
        "time_sec": elapsed,
    }


sample_row = mall_df.iloc[0]

for th in [0.3, 0.4, 0.5, 0.6, 0.7]:
    r = predict_pet_points(sample_row["image_path"], score_threshold=th)
    print(f"threshold={th} | pred_count={r['count']} | gt={sample_row['gt_count']} | time={r['time_sec']:.4f}s")

threshold=0.3 | pred_count=25 | gt=29 | time=0.1626s
threshold=0.4 | pred_count=25 | gt=29 | time=0.1299s
threshold=0.5 | pred_count=25 | gt=29 | time=0.1215s
threshold=0.6 | pred_count=22 | gt=29 | time=0.1228s
threshold=0.7 | pred_count=20 | gt=29 | time=0.1200s

In [44]:
PET_SCORE_THRESHOLD = 0.5

def run_pet_full_metrics(samples_df: pd.DataFrame, distance_threshold: float = 16.0):
    rows = []

    for _, row in tqdm(samples_df.iterrows(), total=len(samples_df)):
        pred = predict_pet_points(
            row["image_path"],
            score_threshold=PET_SCORE_THRESHOLD,
        )

        gt_points = get_gt_points(row["dataset"], row["frame_id"])

        loc = compute_localization_metrics(
            gt_points=gt_points,
            pred_points=pred["points"],
            distance_threshold=distance_threshold,
        )

        pred_count = int(pred["count"])
        gt_count = int(row["gt_count"])

        rows.append({
            "model": "PET",
            "dataset": row["dataset"],
            "frame_id": row["frame_id"],
            "gt_count": gt_count,
            "pred_count": pred_count,
            "abs_error": abs(pred_count - gt_count),
            "sq_error": (pred_count - gt_count) ** 2,
            "time_sec": float(pred["time_sec"]),
            "fps": float(1.0 / pred["time_sec"]) if pred["time_sec"] > 0 else 0.0,
            "tp": loc["tp"],
            "fp": loc["fp"],
            "fn": loc["fn"],
            "precision": loc["precision"],
            "recall": loc["recall"],
            "f1": loc["f1"],
        })

    return pd.DataFrame(rows)


pet_quick_df = run_pet_full_metrics(quick_samples, distance_threshold=16.0)

pet_quick_summary = (
    pet_quick_df
    .groupby(["model", "dataset"])
    .agg(
        frames=("frame_id", "count"),
        mae=("abs_error", "mean"),
        rmse=("sq_error", lambda x: float(np.sqrt(np.mean(x)))),
        avg_fps=("fps", "mean"),
        avg_time_sec=("time_sec", "mean"),
        total_tp=("tp", "sum"),
        total_fp=("fp", "sum"),
        total_fn=("fn", "sum"),
        mean_gt=("gt_count", "mean"),
        mean_pred=("pred_count", "mean"),
    )
    .reset_index()
)

pet_quick_summary["precision"] = (
    pet_quick_summary["total_tp"] /
    (pet_quick_summary["total_tp"] + pet_quick_summary["total_fp"])
)

pet_quick_summary["recall"] = (
    pet_quick_summary["total_tp"] /
    (pet_quick_summary["total_tp"] + pet_quick_summary["total_fn"])
)

pet_quick_summary["f1"] = (
    2 * pet_quick_summary["precision"] * pet_quick_summary["recall"] /
    (pet_quick_summary["precision"] + pet_quick_summary["recall"])
)

display(pet_quick_summary)

  0%|          | 0/200 [00:00<?, ?it/s]

,model,dataset,frames,mae,rmse,avg_fps,avg_time_sec,total_tp,total_fp,total_fn,mean_gt,mean_pred,precision,recall,f1
0,PET,FDST,100,6.48,7.525955,1.304898,0.767167,1900,917,289,21.89,28.17,0.674476,0.867976,0.759089
1,PET,Mall,100,2.80,3.712142,8.249313,0.121383,1689,791,919,26.08,24.80,0.681048,0.647623,0.663915

In [45]:
pet_full_df = run_pet_full_metrics(
    full_samples,
    distance_threshold=16.0
)

pet_full_summary = (
    pet_full_df
    .groupby(["model","dataset"])
    .agg(
        frames=("frame_id","count"),
        mae=("abs_error","mean"),
        rmse=("sq_error", lambda x: float(np.sqrt(np.mean(x)))),
        avg_fps=("fps","mean"),
        avg_time_sec=("time_sec","mean"),
        total_tp=("tp","sum"),
        total_fp=("fp","sum"),
        total_fn=("fn","sum"),
        mean_gt=("gt_count","mean"),
        mean_pred=("pred_count","mean")
    )
    .reset_index()
)

pet_full_summary["precision"] = (
    pet_full_summary["total_tp"]/
    (pet_full_summary["total_tp"]+pet_full_summary["total_fp"])
)

pet_full_summary["recall"] = (
    pet_full_summary["total_tp"]/
    (pet_full_summary["total_tp"]+pet_full_summary["total_fn"])
)

pet_full_summary["f1"] = (
    2*pet_full_summary["precision"]*
    pet_full_summary["recall"]/
    (pet_full_summary["precision"]+
     pet_full_summary["recall"])
)

display(pet_full_summary)

pet_full_df.to_csv(
    BENCH_DIR/"PET_full_predictions_mall_fdst6000.csv",
    index=False
)

pet_full_summary.to_csv(
    BENCH_DIR/"PET_full_summary_mall_fdst6000.csv",
    index=False
)

print("Saved PET benchmark")

  0%|          | 0/8000 [00:00<?, ?it/s]

,model,dataset,frames,mae,rmse,avg_fps,avg_time_sec,total_tp,total_fp,total_fn,mean_gt,mean_pred,precision,recall,f1
0,PET,FDST,6000,3.503667,4.778842,1.792470,0.649029,94477,32524,33040,21.252833,21.166833,0.743908,0.740897,0.742399
1,PET,Mall,2000,3.405500,4.341256,7.868526,0.127155,37748,20890,24567,31.157500,29.319000,0.643746,0.605761,0.624176

Saved PET benchmark

In [47]:
import os
import sys
import torch
from pathlib import Path

STEERER_REPO = REPOS_DIR / "STEERER"
os.chdir(STEERER_REPO)

# Clean possible previous STEERER imports
for mod_name in list(sys.modules.keys()):
    if (
        mod_name == "lib"
        or mod_name.startswith("lib.")
        or mod_name == "configs"
        or mod_name.startswith("configs.")
    ):
        del sys.modules[mod_name]

if str(STEERER_REPO) not in sys.path:
    sys.path.insert(0, str(STEERER_REPO))

if str(STEERER_REPO / "tools") not in sys.path:
    sys.path.insert(0, str(STEERER_REPO / "tools"))

STEERER_WEIGHT_PATH_USE = INPUT_BASE / "steerer-models" / "JHU_mae_54.5_mse_240.6.pth"

print("STEERER repo:", STEERER_REPO)
print("CWD:", os.getcwd())
print("STEERER JHU weight:", STEERER_WEIGHT_PATH_USE)
print("Exists:", STEERER_WEIGHT_PATH_USE.exists())

STEERER repo: /kaggle/working/repos/STEERER
CWD: /kaggle/working/repos/STEERER
STEERER JHU weight: /kaggle/input/datasets/yahiaelgayar/steerer-models/JHU_mae_54.5_mse_240.6.pth
Exists: True

In [48]:
files_to_check = [
    STEERER_REPO / "configs" / "JHU_final.py",
    STEERER_REPO / "configs" / "VGG" / "JHU_vgg19_bn.py",
    STEERER_REPO / "tools" / "test_single_img.py",
    STEERER_REPO / "tools" / "test_cc.py",
]

for p in files_to_check:
    print("\n" + "=" * 80)
    print(p)
    print("=" * 80)

    if not p.exists():
        print("MISSING")
        continue

    with open(p, "r", encoding="utf8", errors="ignore") as f:
        lines = f.readlines()

    for i, line in enumerate(lines[:180]):
        print(f"{i+1:03d}: {line.rstrip()}")

================================================================================
/kaggle/working/repos/STEERER/configs/JHU_final.py
================================================================================
001: gpus = (0, 1,)
002: log_dir = 'exp'
003: workers = 6
004: print_freq = 30
005: seed = 3035
006:
007: network = dict(
008:     backbone="MocHRBackbone",
009:     sub_arch='hrnet48',
010:     counter_type = 'withMOE', #'withMOE' 'baseline'
011:     resolution_num = [0,1,2,3],
012:     loss_weight = [1., 1/2, 1/4., 1/8.],
013:     sigma = [4],
014:     gau_kernel_size = 15,
015:     baseline_loss = False,
016:     pretrained_backbone="../PretrainedModels/hrnetv2_w48_imagenet_pretrained.pth",
017:
018:
019:     head = dict(
020:         type='CountingHead',
021:         fuse_method = 'cat',
022:         in_channels=96,
023:         stages_channel = [384, 192, 96, 48],
024:         inter_layer=[64,32,16],
025:         out_channels=1)
026:     )
027:
028: dataset = dict(
029:     name='JHU',
030:     root='../ProcessedData/JHU/',
031:     test_set='test_val.txt',
032:     train_set='train.txt',
033:     loc_gt = 'test_gt_loc.txt',
034:     num_classes=len(network['resolution_num']),
035:     den_factor=100,
036:     extra_train_set =None
037: )
038:
039:
040:
041: optimizer = dict(
042:     NAME='adamw',
043:     BASE_LR=1e-5,
044:     BETAS=(0.9, 0.999),
045:     WEIGHT_DECAY=1e-4,
046:     EPS= 1.0e-08,
047:     MOMENTUM= 0.9,
048:     AMSGRAD = False,
049:     NESTEROV= True,
050:     )
051:
052:
053: lr_config = dict(
054:     NAME='cosine',
055:     WARMUP_METHOD='linear',
056:     DECAY_EPOCHS=250,
057:     DECAY_RATE = 0.1,
058:     WARMUP_EPOCHS=10,   # the number of epochs to warmup the lr_rate
059:     WARMUP_LR=5.0e-07,
060:     MIN_LR= 1.0e-07
061:   )
062:
063:
064: log_config = dict(
065:     interval=50,
066:     hooks=[
067:         dict(type='TextLoggerHook'),
068:     ])
069:
070: train = dict(
071:     counter='normal',
072:     image_size=(768, 768),  # height width
073:     route_size=(256, 256),  # height, width
074:     base_size=None,
075:     batch_size_per_gpu=8,
076:     shuffle=True,
077:     begin_epoch=0,
078:     end_epoch=1000,
079:     extra_epoch=0,
080:     extra_lr = 0,
081:     #  RESUME: true
082:     resume_path=None,#
083:     flip=True,
084:     multi_scale=True,
085:     scale_factor=(0.75, 1/0.75),
086:     val_span =  [-1000, -600, -400, -200, -200, -100, -100],
087:     downsamplerate= 1,
088:     ignore_label= 255
089: )
090:
091:
092: test = dict(
093:     image_size=(1024, 2048),  # height, width
094:     base_size=None,
095:     loc_base_size=None,
096:     loc_threshold = 0.10 ,
097:     batch_size_per_gpu=1,
098:     patch_batch_size=16,
099:     flip_test=False,
100:     multi_scale=False,
101:     model_file= '',
102: )
103:
104: CUDNN = dict(
105:     BENCHMARK= True,
106:     DETERMINISTIC= False,
107:     ENABLED= True)

================================================================================
/kaggle/working/repos/STEERER/configs/VGG/JHU_vgg19_bn.py
================================================================================
001: # _base_ =[
002: #     '../_base_/datasets/imagenet_bs64_swin_224.py'
003: # ]
004: gpus = (0, 1,)
005: log_dir = 'exp'
006: workers = 12
007: print_freq = 30
008: seed = 3035
009:
010: network = dict(
011:     backbone="VGGBackbone",
012:     sub_arch='vgg19_bn',
013:     counter_type = 'withMOE', #'withMOE' 'baseline'
014:     resolution_num = [0,1,2,3],
015:     loss_weight = [1., 1./2, 1./4, 1./8],
016:     sigma = [4],
017:     gau_kernel_size = 15,
018:     baseline_loss = False,
019:     pretrained_backbone="../PretrainedModels/vgg/",
020:     # '/mnt/petrelfs/hantao/HRNet-Semantic-Segmentation/exp/imagenet/CCFBackbone_hrt_base/ccformer_b_2022-08-16-14-59/Ep_142_acc1_75.12800201416016.pth',
021:
022:     head = dict(
023:         type='CountingHead',
024:         fuse_method = 'cat',
025:         in_channels=96,
026:         stages_channel = [512, 512, 512, 256],
027:         inter_layer=[64,32,16],
028:         out_channels=1)
029: )
030:
031:
032: dataset = dict(
033:     name='JHU',
034:     root='../ProcessedData/JHU/',
035:     test_set='test_val.txt',
036:     train_set='train.txt',
037:     loc_gt = 'test_gt_loc.txt',
038:     num_classes=len(network['resolution_num']),
039:     den_factor=100,
040:     extra_train_set =None
041: )
042:
043:
044: optimizer = dict(
045:     NAME='adamw',
046:     BASE_LR=1e-5,
047:     BETAS=(0.9, 0.999),
048:     WEIGHT_DECAY=1e-4,
049:     EPS= 1.0e-08,
050:     MOMENTUM= 0.9,
051:     AMSGRAD = False,
052:     NESTEROV= True,
053:     )
054:
055:
056: lr_config = dict(
057:     NAME='cosine',
058:     WARMUP_METHOD='linear',
059:     DECAY_EPOCHS=250,
060:     DECAY_RATE = 0.1,
061:     WARMUP_EPOCHS=10,   # the number of epochs to warmup the lr_rate
062:     WARMUP_LR=5.0e-07,
063:     MIN_LR= 1.0e-07
064:   )
065:
066: total_epochs = 210
067:
068: log_config = dict(
069:     interval=50,
070:     hooks=[
071:         dict(type='TextLoggerHook'),
072:     ])
073:
074: train = dict(
075:     counter='normal',
076:     image_size=(768,768),  # height width
077:     route_size=(256, 256),  # height, width
078:     base_size=2048,
079:     batch_size_per_gpu=8,
080:     shuffle=True,
081:     begin_epoch=0,
082:     end_epoch=1000,
083:     extra_epoch=0,
084:     extra_lr = 0,
085:     #  RESUME: true
086:     resume_path=None, #'./exp/SHHB/MocHRBackbone_hrnet48/SHHB_mocHR_small_2022-09-22-09-05/', #'/mnt/petrelfs/hantao/HRNet-Semantic-Segmentation/exp/SHHB/MocHRBackbone_hrnet48/mocHR_small_2022-09-18-14-54/', #'/mnt/petrelfs/hantao/HRNet-Semantic-Segmentation/exp/NWPU/MocHRBackbone_hrnet48/mocHR_small_2022-09-13-16-28/', # '/mnt/petrelfs/hantao/HRNet-Semantic-Segmentation/exp/NWPU/MocHRBackbone_hrnet48/mocHR_small_2022-09-09-21-07/', #'./exp/NWPU/MocHRBackbone_hrnet48/mocHR_small_2022-09-06-20-35/', #'/mnt/petrelfs/hantao/HRNet-Semantic-Segmentation/exp/NWPU/MocHRBackbone_hrnet48/mocHR_small_2022-09-06-13-03/', #'./exp/NWPU/MocHRBackbone_hrnet48/mocHR_small_2022-09-04-19-21/', #'./exp/NWPU/MocBackbone_moc_small/moc_small_2022-08-31-14-41/', #'./exp/NWPU/seg_hrnet/hrt_small_2022-08-07-23-15/',
087:     # './exp/NWPU/seg_hrnet/seg_hrnet_w48_2022-05-27-15-03'
088:     flip=True,
089:     multi_scale=True,
090:     scale_factor=(0.5, 1/0.5),
091:     val_span = [-1000, -600, -400, -200, -200, -100, -100],
092:     downsamplerate= 1,
093:     ignore_label= 255
094: )
095:
096:
097: test = dict(
098:     image_size=(1024, 2048),  # height, width
099:     base_size=2048,
100:     batch_size_per_gpu=1,
101:     patch_batch_size=16,
102:     flip_test=False,
103:     multi_scale=False,
104:     # './exp/NWPU/seg_hrnet/seg_hrnet_w48_nwpu_2022-06-03-23-12/Ep_138_mae_45.79466183813661_mse_116.98580130706075.pth'
105:     # model_file= './exp/SHHB/MocHRBackbone_hrnet48/SHHB_mocHR_small_2022-09-23-17-37/Ep_204_mae_6.745270511772059_mse_11.943930811699868.pth', #'./exp/NWPU/seg_hrnet/seg_hrnet_w48_2022-06-03-23-12/Ep_280_mae_54.884169212251905_mse_226.06904272422108.pth'
106:     # model_file = './exp/SHHB/MocHRBackbone_hrnet48/SHHB_mocHR_small_2022-09-23-17-29/Ep_304_mae_6.403675679919086_mse_11.059794822384989.pth'
107:     model_file = './exp/SHHB/MocHRBackbone_hrnet48/SHHB_HR_2022-10-09-00-42/Ep_703_mae_5.803627611715583_mse_8.761706717939719.pth'
108: )
109:
110: CUDNN = dict(
111:     BENCHMARK= True,
112:     DETERMINISTIC= False,
113:     ENABLED= True)
114:
115:

================================================================================
/kaggle/working/repos/STEERER/tools/test_single_img.py
================================================================================
001: import os
002: import pprint
003: # import _init_paths
004: from lib.core.Counter import Counter
005: from lib.utils.utils import create_logger, random_seed_setting
006: from lib.utils.modelsummary import get_model_summary
007: from lib.core.cc_function import test_cc
008: # import datasets
009: import torch.backends.cudnn as cudnn
010: import torch.nn as nn
011: import torch
012: import numpy as np
013: import timeit
014: import time
015: import logging
016: import argparse
017: from lib.models.build_counter import Baseline_Counter
018: from lib.utils.dist_utils import (
019:     get_dist_info,
020:     init_dist)
021: from mmcv import Config, DictAction
022: import cv2
023: import torchvision.transforms as T
024: from PIL import Image
025:
026: def get_count(img: np.array) -> float:
027:     device = 'cuda' if torch.cuda.is_available() else 'cpu'
028:     config = Config.fromfile('configs/SHHB_final.py')
029:     model = Baseline_Counter(config.network, config.dataset.den_factor, config.train.route_size, device)
030:     pretrained_dict = torch.load('PretrainedModels/SHHB_mae_5.8_mse_8.5.pth')
031:     model.load_state_dict(pretrained_dict,strict=True)
032:     model = model.to(device)
033:     transform = T.Compose([
034:         T.ToPILImage(),
035:         T.Resize((1536, 2048)),
036:         T.ToTensor(),
037:     ])
038:     img = transform(img)
039:     img = img.unsqueeze(0).to(device)
040:     labels = list()
041:     labels.append(torch.zeros(1, 1536, 2048))
042:     labels.append(torch.zeros(1, 768, 1024))
043:     labels.append(torch.zeros(1, 384, 512))
044:     labels.append(torch.zeros(1, 192, 256))
045:     for i in range(len(labels)):
046:         labels[i] = labels[i].to(device)
047:     with torch.no_grad():
048:         result = model(img, labels=labels, mode='val')
049:     pre_den = result['pre_den']['1']
050:     pred_cnt = pre_den.sum().item()
051:     return pred_cnt
052:
053: if __name__ == '__main__':
054:     imgs = [
055:
056:     ]
057:     for i in imgs:
058:         img = cv2.imread(i)
059:         cnt = get_count(img)
060:         print(cnt)

================================================================================
/kaggle/working/repos/STEERER/tools/test_cc.py
================================================================================
001:
002: # ------------------------------------------------------------------------------
003: # Copyright (c) Microsoft
004: # Licensed under the MIT License.
005: # Written by Ke Sun (sunk@mail.ustc.edu.cn)
006: # ------------------------------------------------------------------------------
007: import os
008: import pprint
009: import _init_paths
010: from lib.core.Counter import Counter
011: from lib.utils.utils import create_logger, random_seed_setting
012: from lib.utils.modelsummary import get_model_summary
013: from lib.core.cc_function import test_cc
014: import datasets
015: import torch.backends.cudnn as cudnn
016: import torch.nn as nn
017: import torch
018: import numpy as np
019: import timeit
020: import time
021: import logging
022: import argparse
023: from lib.models.build_counter import Baseline_Counter
024: from lib.utils.dist_utils import (
025:     get_dist_info,
026:     init_dist)
027: from mmcv import Config, DictAction
028:
029:
030: def parse_args():
031:     parser = argparse.ArgumentParser(description='Test crowd counting network')
032:
033:     parser.add_argument('--cfg',
034:                         help='experiment configure file name',
035:                         required=True,
036:                         type=str)
037:     parser.add_argument('--checkpoint',
038:                     help='experiment configure file name',
039:                     required=True,
040:                     type=str)
041:     parser.add_argument('opts',
042:                         help="Modify config options using the command-line",
043:                         default=None,
044:                         nargs=argparse.REMAINDER)
045:     parser.add_argument('--launcher',
046:                         choices=['none', 'pytorch', 'slurm', 'mpi','torchrun'],
047:                         default='none',
048:                         help='job launcher')
049:
050:     parser.add_argument("--local_rank", type=int, default=0)
051:     parser.add_argument(
052:         '--cfg-options',
053:         nargs='+',
054:         action=DictAction,
055:         help='override some settings in the used config, the key-value pair '
056:              'in xxx=yyy format will be merged into config file. If the value to '
057:              'be overwritten is a list, it should be like key="[a,b]" or key=a,b '
058:              'It also allows nested list/tuple values, e.g. key="[(a,b),(c,d)]" '
059:              'Note that the quotation marks are necessary and that no white space '
060:              'is allowed.')
061:     args = parser.parse_args()
062:     if 'LOCAL_RANK' not in os.environ:
063:         os.environ['LOCAL_RANK'] = str(args.local_rank)
064:
065:     return args
066:
067:
068: def main():
069:     args = parse_args()
070:     config = Config.fromfile(args.cfg)
071:
072:     logger, final_output_dir = create_logger(
073:         config, args.cfg, 'test')
074:
075:     logger.info(pprint.pformat(args))
076:     logger.info(pprint.pformat(config))
077:
078:     logger.info('GPU idx:'+os.environ['CUDA_VISIBLE_DEVICES'])
079:     gpus = config.gpus
080:     distributed = torch.cuda.device_count() > 1
081:     if distributed:
082:         torch.cuda.set_device(args.local_rank)
083:         # torch.distributed.init_process_group(
084:         #     backend="nccl", init_method="env://",
085:         # )
086:         init_dist(args.launcher)
087:         # torch.cuda.set_device(args.local_rank)
088:         if args.launcher == 'pytorch':
089:             args.local_rank = int(os.environ["LOCAL_RANK"])
090:         else:
091:             rank, world_size = get_dist_info()
092:             args.local_rank = rank
093:
094:     # cudnn related setting
095:     random_seed_setting(config)
096:
097:     # build model
098:     device = torch.device('cuda:{}'.format(args.local_rank))
099:
100:     model = Baseline_Counter(config.network,config.dataset.den_factor,config.train.route_size,device)
101:
102:     # dump_input = torch.rand(
103:     #     (1, 3, config.TRAIN.IMAGE_SIZE[1], config.TRAIN.IMAGE_SIZE[0])
104:     # )
105:     # logger.info(get_model_summary(model.cuda(), dump_input.cuda()))
106:
107:     if args.checkpoint:
108:         model_state_file = args.checkpoint
109:     elif config.test.model_file:
110:         model_state_file = config.test.model_file
111:     else:
112:         model_state_file = os.path.join(final_output_dir,
113:                                         'final_state.pth')
114:
115:     logger.info('=> loading model from {}'.format(model_state_file))
116:
117:     pretrained_dict = torch.load(model_state_file)
118:
119:
120:     model.load_state_dict(pretrained_dict,strict=False)
121:
122:
123:     model = model.to(device)
124:
125:     # prepare data
126:     test_dataset = eval('datasets.' + config.dataset.name)(
127:         root=config.dataset.root,
128:         list_path=config.dataset.test_set,
129:         num_samples=None,
130:         multi_scale=False,
131:         flip=False,
132:         base_size=config.test.base_size,
133:         downsample_rate=1)
134:
135:     testloader = torch.utils.data.DataLoader(
136:         test_dataset,
137:         batch_size=1,
138:         shuffle=False,
139:         num_workers=8,  # config.WORKERS,
140:         pin_memory=True)
141:
142:     start = timeit.default_timer()
143:     if 'test' in  config.dataset.test_set or 'val' in config.dataset.test_set:
144:
145:         mae, mse, nae,save_count_txt = test_cc(config, test_dataset, testloader, model,
146:                                 test_dataset.mean, test_dataset.std,
147:                                 sv_dir=final_output_dir, sv_pred=False,logger=logger
148:                                 )
149:
150:         msg = 'mae: {: 4.4f}, mse: {: 4.4f}, \
151:                nae: {: 4.4f}, Class IoU: '.format(mae,
152:                                                   mse, nae)
153:         logging.info(msg)
154:
155:
156:     with open(final_output_dir+'_submit_SIC.txt', 'w') as f:
157:         f.write(save_count_txt)
158:
159:     end = timeit.default_timer()
160:     logger.info('Mins: %d' % np.int32((end - start) / 60))
161:     logger.info('Done')
162:
163:
164: if __name__ == '__main__':
165:     main()

In [49]:
from mmcv import Config
from lib.models.build_counter import Baseline_Counter

cfg = Config.fromfile(
    str(STEERER_REPO / "configs" / "JHU_final.py")
)

device = DEVICE

steerer_model = Baseline_Counter(
    cfg.network,
    cfg.dataset.den_factor,
    cfg.train.route_size,
    device
)

ckpt = torch.load(
    STEERER_WEIGHT_PATH_USE,
    map_location="cpu"
)

missing, unexpected = steerer_model.load_state_dict(
    ckpt,
    strict=False
)

steerer_model = steerer_model.to(DEVICE)
steerer_model.eval()

print("STEERER loaded")
print("Missing:", len(missing))
print("Unexpected:", len(unexpected))

ModuleNotFoundError: No module named 'mmcv'

In [52]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "-q",
    "mmcv==1.7.1"
])

print("Installed mmcv==1.7.1")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 605.4/605.4 kB 21.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.8/46.8 kB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.2/256.2 kB 17.6 MB/s eta 0:00:00
Installed mmcv==1.7.1

In [53]:
import mmcv
from mmcv import Config

print("mmcv version:", mmcv.__version__)
print("Config import works")

mmcv version: 1.7.1
Config import works

/usr/local/lib/python3.12/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(

In [54]:
from mmcv import Config
from lib.models.build_counter import Baseline_Counter

cfg = Config.fromfile(
    str(STEERER_REPO / "configs" / "JHU_final.py")
)

device = DEVICE

steerer_model = Baseline_Counter(
    cfg.network,
    cfg.dataset.den_factor,
    cfg.train.route_size,
    device
)

ckpt = torch.load(
    STEERER_WEIGHT_PATH_USE,
    map_location="cpu"
)

missing, unexpected = steerer_model.load_state_dict(
    ckpt,
    strict=False
)

steerer_model = steerer_model.to(DEVICE)
steerer_model.eval()

print("STEERER loaded")
print("Missing:", len(missing))
print("Unexpected:", len(unexpected))

/usr/local/lib/python3.12/dist-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

ModuleNotFoundError: No module named 'dict_recursive_update'

In [55]:
import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "-q",
    "dict-recursive-update"
])

print("Installed dict-recursive-update")

Installed dict-recursive-update

In [56]:
from mmcv import Config
from lib.models.build_counter import Baseline_Counter

cfg = Config.fromfile(
    str(STEERER_REPO / "configs" / "JHU_final.py")
)

device = DEVICE

steerer_model = Baseline_Counter(
    cfg.network,
    cfg.dataset.den_factor,
    cfg.train.route_size,
    device
)

ckpt = torch.load(
    STEERER_WEIGHT_PATH_USE,
    map_location="cpu"
)

missing, unexpected = steerer_model.load_state_dict(
    ckpt,
    strict=False
)

steerer_model = steerer_model.to(DEVICE)
steerer_model.eval()

print("STEERER loaded")
print("Missing:", len(missing))
print("Unexpected:", len(unexpected))

STEERER loaded
Missing: 0
Unexpected: 1

In [57]:
import cv2
import time
import torch
import torchvision.transforms as T
from PIL import Image

steerer_transform = T.Compose([
    T.ToPILImage(),
    T.Resize((1024, 2048)),
    T.ToTensor(),
])

@torch.no_grad()
def inspect_steerer_output(image_path: str):
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(image_path)

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    x = steerer_transform(img).unsqueeze(0).to(DEVICE)

    labels = [
        torch.zeros(1, 1024, 2048).to(DEVICE),
        torch.zeros(1, 512, 1024).to(DEVICE),
        torch.zeros(1, 256, 512).to(DEVICE),
        torch.zeros(1, 128, 256).to(DEVICE),
    ]

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    start = time.perf_counter()

    result = steerer_model(x, labels=labels, mode="val")

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    elapsed = time.perf_counter() - start

    print("Result type:", type(result))
    print("Time:", elapsed)

    if isinstance(result, dict):
        print("Keys:", result.keys())

        for k, v in result.items():
            if isinstance(v, dict):
                print(k, "dict keys:", v.keys())
                for kk, vv in v.items():
                    if torch.is_tensor(vv):
                        print(" ", kk, vv.shape, float(vv.min()), float(vv.max()), float(vv.sum()))
            elif torch.is_tensor(v):
                print(k, v.shape, float(v.min()), float(v.max()), float(v.sum()))
            else:
                print(k, type(v))

    return result, elapsed


steerer_out, steerer_time = inspect_steerer_output(
    mall_df.iloc[0]["image_path"]
)

Result type: <class 'dict'>
Time: 0.5395413339992956
Keys: dict_keys(['pre_den', 'gt_den', 'losses'])
pre_den dict keys: dict_keys(['1', '2', '4', '8'])
  1 torch.Size([1, 1, 1024, 2048]) 0.0 0.0057325661182403564 23.50851058959961
  2 torch.Size([1, 1, 512, 1024]) 0.0 0.023469487205147743 17.771785736083984
  4 torch.Size([1, 1, 256, 512]) 0.0 0.002840672619640827 4.115779876708984
  8 torch.Size([1, 1, 128, 256]) 0.0 0.014321057125926018 11.433971405029297
gt_den dict keys: dict_keys(['1', '2', '4', '8'])
  1 torch.Size([1, 1, 1024, 2048]) 0.0 0.0 0.0
  2 torch.Size([1, 1, 512, 1024]) 0.0 0.0 0.0
  4 torch.Size([1, 1, 256, 512]) 0.0 0.0 0.0
  8 torch.Size([1, 1, 128, 256]) 0.0 0.0 0.0
losses torch.Size([]) 0.0001837913296185434 0.0001837913296185434 0.0001837913296185434

In [58]:
def extract_points_from_density_map(
    den_map: np.ndarray,
    threshold: float = 0.001,
    nms_kernel: int = 15,
):
    den_map = np.squeeze(den_map)
    den_map = np.maximum(den_map, 0)

    local_max = cv2.dilate(den_map, np.ones((nms_kernel, nms_kernel), np.uint8))
    peaks = (den_map == local_max) & (den_map >= threshold)

    ys, xs = np.where(peaks)

    points = []
    for x, y in zip(xs, ys):
        points.append((float(x), float(y), float(den_map[y, x])))

    return points


@torch.no_grad()
def predict_steerer_points(
    image_path: str,
    threshold: float = 0.001,
    nms_kernel: int = 15,
):
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(image_path)

    original_h, original_w = img.shape[:2]

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    x = steerer_transform(img_rgb).unsqueeze(0).to(DEVICE)

    labels = [
        torch.zeros(1, 1024, 2048).to(DEVICE),
        torch.zeros(1, 512, 1024).to(DEVICE),
        torch.zeros(1, 256, 512).to(DEVICE),
        torch.zeros(1, 128, 256).to(DEVICE),
    ]

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    start = time.perf_counter()
    result = steerer_model(x, labels=labels, mode="val")

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    elapsed = time.perf_counter() - start

    den = result["pre_den"]["1"].squeeze().detach().cpu().numpy()

    raw_count = float(den.sum())

    # Extract peaks on resized map 1024x2048
    raw_points = extract_points_from_density_map(
        den,
        threshold=threshold,
        nms_kernel=nms_kernel,
    )

    # Scale points back to original image coordinates
    scale_x = original_w / 2048.0
    scale_y = original_h / 1024.0

    pred_points = []
    for x_map, y_map, score in raw_points:
        x_orig = x_map * scale_x
        y_orig = y_map * scale_y

        if 0 <= x_orig < original_w and 0 <= y_orig < original_h:
            pred_points.append((x_orig, y_orig, score))

    return {
        "count": raw_count,
        "points": pred_points,
        "time_sec": elapsed,
    }


sample_row = mall_df.iloc[0]

for th in [0.0005, 0.001, 0.0015, 0.002, 0.003]:
    r = predict_steerer_points(
        sample_row["image_path"],
        threshold=th,
        nms_kernel=15,
    )
    print(
        f"threshold={th} | raw_count={r['count']:.2f} | "
        f"points={len(r['points'])} | gt={sample_row['gt_count']} | "
        f"time={r['time_sec']:.4f}s"
    )

threshold=0.0005 | raw_count=23.51 | points=26 | gt=29 | time=0.4903s
threshold=0.001 | raw_count=23.51 | points=24 | gt=29 | time=0.4277s
threshold=0.0015 | raw_count=23.51 | points=24 | gt=29 | time=0.4287s
threshold=0.002 | raw_count=23.51 | points=20 | gt=29 | time=0.4288s
threshold=0.003 | raw_count=23.51 | points=17 | gt=29 | time=0.4308s

In [59]:
STEERER_THRESHOLD = 0.0005
STEERER_NMS_KERNEL = 15

def run_steerer_full_metrics(samples_df: pd.DataFrame, distance_threshold: float = 16.0):
    rows = []

    for _, row in tqdm(samples_df.iterrows(), total=len(samples_df)):
        pred = predict_steerer_points(
            row["image_path"],
            threshold=STEERER_THRESHOLD,
            nms_kernel=STEERER_NMS_KERNEL,
        )

        gt_points = get_gt_points(row["dataset"], row["frame_id"])

        loc = compute_localization_metrics(
            gt_points=gt_points,
            pred_points=pred["points"],
            distance_threshold=distance_threshold,
        )

        pred_count = float(pred["count"])
        gt_count = float(row["gt_count"])

        rows.append({
            "model": "STEERER",
            "dataset": row["dataset"],
            "frame_id": row["frame_id"],
            "gt_count": gt_count,
            "pred_count": pred_count,
            "abs_error": abs(pred_count - gt_count),
            "sq_error": (pred_count - gt_count) ** 2,
            "time_sec": float(pred["time_sec"]),
            "fps": float(1.0 / pred["time_sec"]) if pred["time_sec"] > 0 else 0.0,
            "tp": loc["tp"],
            "fp": loc["fp"],
            "fn": loc["fn"],
            "precision": loc["precision"],
            "recall": loc["recall"],
            "f1": loc["f1"],
            "num_pred_points": len(pred["points"]),
        })

    return pd.DataFrame(rows)


steerer_full_df = run_steerer_full_metrics(
    full_samples,
    distance_threshold=16.0
)

steerer_full_summary = (
    steerer_full_df
    .groupby(["model", "dataset"])
    .agg(
        frames=("frame_id", "count"),
        mae=("abs_error", "mean"),
        rmse=("sq_error", lambda x: float(np.sqrt(np.mean(x)))),
        avg_fps=("fps", "mean"),
        avg_time_sec=("time_sec", "mean"),
        total_tp=("tp", "sum"),
        total_fp=("fp", "sum"),
        total_fn=("fn", "sum"),
        mean_gt=("gt_count", "mean"),
        mean_pred=("pred_count", "mean"),
        mean_pred_points=("num_pred_points", "mean"),
    )
    .reset_index()
)

steerer_full_summary["precision"] = (
    steerer_full_summary["total_tp"] /
    (steerer_full_summary["total_tp"] + steerer_full_summary["total_fp"])
)

steerer_full_summary["recall"] = (
    steerer_full_summary["total_tp"] /
    (steerer_full_summary["total_tp"] + steerer_full_summary["total_fn"])
)

steerer_full_summary["f1"] = (
    2 * steerer_full_summary["precision"] * steerer_full_summary["recall"] /
    (steerer_full_summary["precision"] + steerer_full_summary["recall"])
)

display(steerer_full_summary)

steerer_full_df.to_csv(
    BENCH_DIR / "STEERER_full_predictions_mall_fdst6000.csv",
    index=False
)

steerer_full_summary.to_csv(
    BENCH_DIR / "STEERER_full_summary_mall_fdst6000.csv",
    index=False
)

print("Saved STEERER predictions:", BENCH_DIR / "STEERER_full_predictions_mall_fdst6000.csv")
print("Saved STEERER summary:", BENCH_DIR / "STEERER_full_summary_mall_fdst6000.csv")

  0%|          | 0/8000 [00:00<?, ?it/s]

,model,dataset,frames,mae,rmse,avg_fps,avg_time_sec,total_tp,total_fp,total_fn,mean_gt,mean_pred,mean_pred_points,precision,recall,f1
0,STEERER,FDST,6000,3.104902,3.979735,2.226287,0.449184,105990,23171,21527,21.252833,19.011621,21.526833,0.820604,0.831183,0.825860
1,STEERER,Mall,2000,10.050796,10.626403,2.231511,0.448177,36359,10980,25956,31.157500,21.107229,23.669500,0.768056,0.583471,0.663159

Saved STEERER predictions: /kaggle/working/benchmark_results/STEERER_full_predictions_mall_fdst6000.csv
Saved STEERER summary: /kaggle/working/benchmark_results/STEERER_full_summary_mall_fdst6000.csv

In [60]:
import pandas as pd

fidtm = pd.read_csv(
    "/kaggle/working/benchmark_results/FIDTM_full_summary_mall_fdst6000.csv"
)

pet = pd.read_csv(
    "/kaggle/working/benchmark_results/PET_full_summary_mall_fdst6000.csv"
)

steerer = pd.read_csv(
    "/kaggle/working/benchmark_results/STEERER_full_summary_mall_fdst6000.csv"
)

final_df = pd.concat(
    [fidtm, pet, steerer],
    ignore_index=True
)

display(final_df)

final_df.to_csv(
    "/kaggle/working/benchmark_results/benchmark_final_comparison.csv",
    index=False
)

final_df.to_excel(
    "/kaggle/working/benchmark_results/benchmark_final_comparison.xlsx",
    index=False
)

print("saved")

,model,dataset,frames,mae,rmse,avg_fps,avg_time_sec,total_tp,total_fp,total_fn,mean_gt,mean_pred,precision,recall,f1,mean_pred_points
0,FIDTM,FDST,6000,3.613500,4.736578,2.269182,0.489558,89871,27295,37646,21.252833,19.527667,0.767040,0.704777,0.734591,NaN
1,FIDTM,Mall,2000,3.167000,3.937893,8.957016,0.113403,41897,15786,20418,31.157500,28.841500,0.726332,0.672342,0.698295,NaN
2,PET,FDST,6000,3.503667,4.778842,1.792470,0.649029,94477,32524,33040,21.252833,21.166833,0.743908,0.740897,0.742399,NaN
3,PET,Mall,2000,3.405500,4.341256,7.868526,0.127155,37748,20890,24567,31.157500,29.319000,0.643746,0.605761,0.624176,NaN
4,STEERER,FDST,6000,3.104902,3.979735,2.226287,0.449184,105990,23171,21527,21.252833,19.011621,0.820604,0.831183,0.825860,21.526833
5,STEERER,Mall,2000,10.050796,10.626403,2.231511,0.448177,36359,10980,25956,31.157500,21.107229,0.768056,0.583471,0.663159,23.669500

saved

In [61]:
import os

for f in os.listdir("/kaggle/working/benchmark_results"):
    print(f)

FIDTM_full_predictions_mall_fdst6000.csv
STEERER_full_predictions_mall_fdst6000.csv
STEERER_full_summary_mall_fdst6000.csv
PET_full_predictions_mall_fdst6000.csv
benchmark_samples_mall_fdst_6000.csv
benchmark_final_comparison.csv
PET_full_summary_mall_fdst6000.csv
benchmark_final_comparison.xlsx
FIDTM_full_summary_mall_fdst6000.csv